# Emissions

In [1]:
import pandas as pd

In [ ]:
dfMap = pd.read_excel("./extdata/rice50_gcam71_mappings.xlsx")
dfMap.head()

  Country ISO Code Country Name RICE 50+ Name within RICE     GCAM v7.1
0              AUS    Australia      aus              aus  Australia_NZ
1              NZL  New Zealand     osea             osea  Australia_NZ
2              CHN        China      chn              chn         China
3              HKG    Hong Kong   rjan57           rjan57         China
4              JPN        Japan      jpn              jpn         Japan

In [3]:
# check total CO2 emissions by country for 2018 in the EDGAR 2023 data
dfEdgar = pd.read_excel("./extdata/EDGARv8.0_FT2022_GHG_booklet_2023.xlsx", sheet_name='GHG_totals_by_country')
dfEdgar

,EDGAR Country Code,Country,1970,1971,1972,1973,1974,1975,1976,1977,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,ABW,Aruba,0.045176,0.050063,0.060857,0.065847,0.065108,0.079128,0.078179,0.088896,...,0.463848,0.475081,0.476461,0.494114,0.467189,0.502077,0.575822,0.494731,0.479192,0.496683
1,AFG,Afghanistan,17.336192,17.292793,15.342251,15.966060,17.278443,17.984253,17.989107,18.153414,...,30.899954,31.214446,31.208495,30.567230,31.773007,31.439840,30.322851,28.150674,28.953697,29.117879
2,AGO,Angola,20.138364,20.018416,22.721001,24.375911,25.083208,23.889924,19.960419,24.620945,...,82.985493,85.186645,90.110604,87.096037,81.888045,78.215749,77.435411,71.682513,69.613898,66.480058
3,AIA,Anguilla,0.004256,0.004258,0.004358,0.004201,0.004451,0.004692,0.004526,0.004627,...,0.033171,0.033174,0.033318,0.033731,0.034494,0.033631,0.033000,0.028107,0.027267,0.028099
4,AIR,International Aviation,171.160455,171.147982,181.492019,189.261213,182.123246,176.107638,176.412012,192.354128,...,488.025465,503.952576,532.878284,555.785220,591.079314,617.430356,627.478301,299.325868,345.376002,425.963735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,ZWE,Zimbabwe,22.245786,22.859421,22.516027,24.140295,24.239679,23.566684,24.709480,23.932646,...,32.927064,30.691499,31.610375,29.676863,29.174904,31.273375,30.207339,28.341567,29.525357,30.190141
210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,EU27,EU27,4611.325766,4637.851097,4788.933368,5005.025057,4963.517082,4878.009116,5145.629069,5133.688874,...,4019.150279,3869.441688,3922.022084,3926.561741,3952.329493,3870.920359,3713.097654,3427.439824,3617.735706,3587.796150
212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,GLOBAL TOTAL,GLOBAL TOTAL,24497.544419,24582.920914,25521.454040,26733.859337,26742.384120,26798.454097,27950.655931,28635.109842,...,49875.675088,50242.997508,50134.383764,50343.044450,51195.419111,52398.143260,52557.335275,50632.309454,53056.607721,53786.038909

In [4]:
# Open World Bank Data
dfWorldBank = pd.read_csv("./extdata/API_EN.GHG.CO2.MT.CE.AR5_DS2_en_csv_v2_15981.csv", skiprows=[0, 1, 2, 3])
dfWorldBank.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,Aruba,ABW,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,...,0.4620,0.4849,0.4666,0.4659,0.5579,0.4526,0.5006,0.5027,0.5300,NaN
1,Africa Eastern and Southern,AFE,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,...,621.8665,628.5365,637.9068,645.8367,654.5401,578.0520,606.3945,588.4335,579.8655,NaN
2,Afghanistan,AFG,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,...,8.3465,7.5276,8.0661,7.9320,7.2491,7.0541,7.9308,8.2599,8.7073,NaN
3,Africa Western and Central,AFW,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,...,208.8912,217.4430,218.2637,230.4901,240.4359,235.9365,249.1554,251.4104,245.6408,NaN
4,Angola,AGO,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,NaN,NaN,NaN,NaN,NaN,NaN,...,33.0975,31.2858,27.9421,26.2589,27.5732,20.7109,25.2628,27.3530,28.2299,NaN

In [5]:
# Find missing values of EDGAR 2023 data from World Bank data

# Prepare EDGAR data
dfLeft = dfEdgar[['EDGAR Country Code', 'Country', 2018]].iloc[:210]
# Prepare World Bank data
dfRight = dfWorldBank[['Country Name', 'Country Code', '2018']]
# Merge two data sets
dfM = dfLeft.merge(dfRight, left_on='EDGAR Country Code', right_on='Country Code', how='outer')

# Find missing values of EDGAR 2023 data from World Bank data
dfM['emiss_co2_2018_mtc'] = dfM[2018].fillna(dfM['2018'] / 3.66667)

# Abbreviate Country Code Variable by CC
dfM['CC'] = dfM['EDGAR Country Code'].fillna(dfM['Country Code'])
dfM[['CC', 'emiss_co2_2018_mtc']]

      CC  emiss_co2_2018_mtc
0    ABW            0.502077
1    AFE          176.137122
2    AFG           31.439840
3    AFW           62.860879
4    AGO           78.215749
..   ...                 ...
276  XKX                 NaN
277  YEM           34.853295
278  ZAF          605.788699
279  ZMB           28.423766
280  ZWE           31.273375

[281 rows x 2 columns]

In [6]:
# Compare mapping data and emissions data 
lstCheck = []
for country in dfMap['Country ISO Code'].unique():
    if country not in dfM['CC'].unique():
        lstCheck.append(country)
print(lstCheck)

[]

In [7]:
dfM['Country ISO Code'] = dfM['CC']

In [8]:
# Merge Map data and emissions data
dfMapEmiss = dfMap.merge(dfM[['Country ISO Code', 'emiss_co2_2018_mtc']], on='Country ISO Code', how='left')
dfMapEmiss

,Country ISO Code,Country Name,RICE 50+,Name within RICE,GCAM v7.1,emiss_co2_2018_mtc
0,AUS,Australia,aus,aus,Australia_NZ,597.774097
1,NZL,New Zealand,osea,osea,Australia_NZ,87.715676
2,CHN,China,chn,chn,China,14296.571168
3,HKG,Hong Kong,rjan57,rjan57,China,50.490156
4,JPN,Japan,jpn,jpn,Japan,1265.994721
...,...,...,...,...,...,...
194,TUV,Tuvalu,osea,osea,Southeast Asia,0.000000
195,UZB,Uzbekistan,oeu,oeu,Central Asia,213.167964
196,VUT,Vanuatu,osea,osea,Southeast Asia,0.693003
197,YEM,Yemen,golf57,golf57,Middle East,34.853295
198,TWN,Taiwan,chn,chn,Taiwan,317.943164

In [9]:
dfMapEmiss[dfMapEmiss['emiss_co2_2018_mtc'].isna()]

,Country ISO Code,Country Name,RICE 50+,Name within RICE,GCAM v7.1,emiss_co2_2018_mtc
122,AND,Andorra,ris,ris,EU-15,NaN
155,IMN,Isle of Man,ris,ris,EU-15,NaN
157,XKX,Kosovo,ris,ris,Europe_Non_EU,NaN
162,LIE,Liechtenstein,ris,ris,European Free Trade Association,NaN
171,MCO,Monaco,ris,ris,EU-15,NaN
172,MNE,Montenegro,ris,ris,Europe_Non_EU,NaN
175,PSE,Palestinian Territories,meme,meme,Middle East,NaN
182,SMR,San Marino,ris,ris,EU-15,NaN
183,SRB,Serbia,ris,ris,Europe_Non_EU,NaN

# GDP/Population

In [10]:
# Open WEO data
dfWeo = pd.read_csv("./extdata/WEOOct2024all.csv", encoding='windows-1252', thousands=',')
dfWeo.head()

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2021,2022,2023,2024,2025,2026,2027,2028,2029,Estimates Start After
0,512,AFG,NGDP_R,Afghanistan,"Gross domestic product, constant prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,101.45","1,032.71","1,060.71",NaN,NaN,NaN,NaN,NaN,NaN,2024.0
1,512,AFG,NGDP_RPCH,Afghanistan,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,Units,"See notes for: Gross domestic product, consta...",NaN,...,-14.542,-6.24,2.711,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
2,512,AFG,NGDP,Afghanistan,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,NaN,...,"1,251.17","1,283.44","1,357.28",NaN,NaN,NaN,NaN,NaN,NaN,2024.0
3,512,AFG,NGDPD,Afghanistan,"Gross domestic product, current prices",Values are based upon GDP in national currency...,U.S. dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,14.278,14.501,17.329,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,85.768,86.149,91.668,NaN,NaN,NaN,NaN,NaN,NaN,2024.0

In [11]:
dfGdPop = dfWeo[dfWeo['WEO Subject Code'].isin(['PPPGDP', 'LP'])].copy()
dfGdPop

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2021,2022,2023,2024,2025,2026,2027,2028,2029,Estimates Start After
4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,85.768,86.149,91.668,NaN,NaN,NaN,NaN,NaN,NaN,2024.0
26,512,AFG,LP,Afghanistan,Population,"For census purposes, the total population of t...",Persons,Millions,"Source: United Nations, Department of Economic...",NaN,...,40.099,41.142,42.171,NaN,NaN,NaN,NaN,NaN,NaN,2023.0
48,914,ALB,PPPGDP,Albania,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",5.705,...,45.725,51.364,55.049,58.196,61.261,64.583,68.044,71.694,75.541,2022.0
70,914,ALB,LP,Albania,Population,"For census purposes, the total population of t...",Persons,Millions,Source: National Statistics Office. INSTAT Lat...,2.672,...,2.812,2.778,2.75,2.722,2.695,2.668,2.668,2.668,2.668,2021.0
92,612,DZA,PPPGDP,Algeria,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",77.897,...,649.015,720.43,776.956,826.136,866.721,904.9,941.152,978.759,"1,017.85",2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,474,YEM,LP,Yemen,Population,"For census purposes, the total population of t...",Persons,Millions,"Source: United Nations, Department of Economic...",NaN,...,32.641,33.322,34.071,34.829,35.611,36.39,37.174,37.957,38.742,2022.0
8540,754,ZMB,PPPGDP,Zambia,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",6.927,...,68.672,77.43,84.545,88.56,96.136,103.653,111.437,119.269,127.401,2022.0
8562,754,ZMB,LP,Zambia,Population,"For census purposes, the total population of t...",Persons,Millions,Source: Other Latest actual data: 2022 Primary...,5.551,...,19.473,20.018,20.57,21.135,21.707,22.286,22.874,23.469,24.07,2022.0
8584,698,ZWE,PPPGDP,Zimbabwe,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,66.518,75.636,82.541,86.162,93.032,99.038,104.437,110.036,115.938,2022.0
8606,698,ZWE,LP,Zimbabwe,Population,"For census purposes, the total population of t...",Persons,Millions,Source: National Statistics Office Latest actu...,7.092,...,15.904,16.229,16.624,16.993,17.36,17.729,18.104,18.488,18.882,2017.0

In [12]:
lstCheck = []
for country in dfMap['Country ISO Code'].unique():
    if country not in dfGdPop['ISO'].unique():
        lstCheck.append(country)
print(lstCheck)

['BMU', 'CUB', 'FRO', 'GRL', 'IMN', 'XKX', 'LIE', 'MCO', 'PSE']

In [13]:
dfGdPop['Country ISO Code'] = dfGdPop['ISO']

In [14]:
dfGdp = dfGdPop[dfGdPop['WEO Subject Code'] == 'PPPGDP'].copy()
dfGdp['pppgdp_2018'] = dfGdp['2018']
dfGdp.head()

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2023,2024,2025,2026,2027,2028,2029,Estimates Start After,Country ISO Code,pppgdp_2018
4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,91.668,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,AFG,89.369
48,914,ALB,PPPGDP,Albania,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",5.705,...,55.049,58.196,61.261,64.583,68.044,71.694,75.541,2022.0,ALB,38.691
92,612,DZA,PPPGDP,Algeria,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",77.897,...,776.956,826.136,866.721,904.9,941.152,978.759,"1,017.85",2023.0,DZA,583.472
136,171,AND,PPPGDP,Andorra,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",NaN,...,5.735,5.955,6.16,6.368,6.583,6.804,7.033,2023.0,AND,4.152
180,614,AGO,PPPGDP,Angola,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",12.494,...,357.562,374.937,392.395,412.748,434.308,457.135,481.331,2022.0,AGO,259.089

In [15]:
dfGdp.columns

Index(['WEO Country Code', 'ISO', 'WEO Subject Code', 'Country',
       'Subject Descriptor', 'Subject Notes', 'Units', 'Scale',
       'Country/Series-specific Notes', '1980', '1981', '1982', '1983', '1984',
       '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029',
       'Estimates Start After', 'Country ISO Code', 'pppgdp_2018'],
      dtype='object')

In [16]:
dfMapEmissGdp = dfMapEmiss.merge(dfGdp[['Country ISO Code', 'pppgdp_2018']], on='Country ISO Code', how='left')
dfMapEmissGdp

,Country ISO Code,Country Name,RICE 50+,Name within RICE,GCAM v7.1,emiss_co2_2018_mtc,pppgdp_2018
0,AUS,Australia,aus,aus,Australia_NZ,597.774097,"1,290.18"
1,NZL,New Zealand,osea,osea,Australia_NZ,87.715676,205.758
2,CHN,China,chn,chn,China,14296.571168,"22,368.20"
3,HKG,Hong Kong,rjan57,rjan57,China,50.490156,453.865
4,JPN,Japan,jpn,jpn,Japan,1265.994721,"5,344.06"
...,...,...,...,...,...,...,...
194,TUV,Tuvalu,osea,osea,Southeast Asia,0.000000,0.045
195,UZB,Uzbekistan,oeu,oeu,Central Asia,213.167964,263.156
196,VUT,Vanuatu,osea,osea,Southeast Asia,0.693003,0.8
197,YEM,Yemen,golf57,golf57,Middle East,34.853295,62.366
198,TWN,Taiwan,chn,chn,Taiwan,317.943164,"1,180.13"

In [17]:
dfMapEmissGdp[dfMapEmissGdp['pppgdp_2018'].isna()]

,Country ISO Code,Country Name,RICE 50+,Name within RICE,GCAM v7.1,emiss_co2_2018_mtc,pppgdp_2018
129,BMU,Bermuda,rcam,rcam,Central America and Caribbean,0.345980,NaN
139,CUB,Cuba,rcam,rcam,Central America and Caribbean,47.894372,NaN
144,FRO,Faroe Islands,ris,ris,EU-15,0.050812,NaN
148,GRL,Greenland,ris,ris,EU-15,0.584499,NaN
155,IMN,Isle of Man,ris,ris,EU-15,NaN,NaN
157,XKX,Kosovo,ris,ris,Europe_Non_EU,NaN,NaN
162,LIE,Liechtenstein,ris,ris,European Free Trade Association,NaN,NaN
171,MCO,Monaco,ris,ris,EU-15,NaN,NaN
175,PSE,Palestinian Territories,meme,meme,Middle East,NaN,NaN
190,SYR,Syria,meme,meme,Middle East,45.905388,NaN

In [18]:
dfPop = dfGdPop[dfGdPop['WEO Subject Code'] == 'LP'].copy()
dfPop['pop_2018'] = dfPop['2018']
dfPop.head()

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2023,2024,2025,2026,2027,2028,2029,Estimates Start After,Country ISO Code,pop_2018
26,512,AFG,LP,Afghanistan,Population,"For census purposes, the total population of t...",Persons,Millions,"Source: United Nations, Department of Economic...",NaN,...,42.171,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,AFG,36.687
70,914,ALB,LP,Albania,Population,"For census purposes, the total population of t...",Persons,Millions,Source: National Statistics Office. INSTAT Lat...,2.672,...,2.75,2.722,2.695,2.668,2.668,2.668,2.668,2021.0,ALB,2.866
114,612,DZA,LP,Algeria,Population,"For census purposes, the total population of t...",Persons,Millions,Source: National Statistics Office Latest actu...,18.666,...,45.973,46.626,47.251,47.851,48.425,49.006,49.594,2019.0,DZA,42.578
158,171,AND,LP,Andorra,Population,"For census purposes, the total population of t...",Persons,Millions,Source: National Statistics Office Latest actu...,NaN,...,0.085,0.087,0.089,0.09,0.092,0.094,0.096,2023.0,AND,0.076
202,614,AGO,LP,Angola,Population,"For census purposes, the total population of t...",Persons,Millions,Source: National Statistics Office Latest actu...,8.272,...,36.961,38.255,39.594,40.98,42.414,43.898,45.435,2021.0,AGO,31.274

In [19]:
dfMapEmissGdPop = dfMapEmissGdp.merge(dfPop[['Country ISO Code', 'pop_2018']], on='Country ISO Code', how='left')
dfMapEmissGdPop

,Country ISO Code,Country Name,RICE 50+,Name within RICE,GCAM v7.1,emiss_co2_2018_mtc,pppgdp_2018,pop_2018
0,AUS,Australia,aus,aus,Australia_NZ,597.774097,"1,290.18",25.146
1,NZL,New Zealand,osea,osea,Australia_NZ,87.715676,205.758,4.902
2,CHN,China,chn,chn,China,14296.571168,"22,368.20","1,405.41"
3,HKG,Hong Kong,rjan57,rjan57,China,50.490156,453.865,7.488
4,JPN,Japan,jpn,jpn,Japan,1265.994721,"5,344.06",126.495
...,...,...,...,...,...,...,...,...
194,TUV,Tuvalu,osea,osea,Southeast Asia,0.000000,0.045,0.011
195,UZB,Uzbekistan,oeu,oeu,Central Asia,213.167964,263.156,32.657
196,VUT,Vanuatu,osea,osea,Southeast Asia,0.693003,0.8,0.285
197,YEM,Yemen,golf57,golf57,Middle East,34.853295,62.366,30.415
198,TWN,Taiwan,chn,chn,Taiwan,317.943164,"1,180.13",23.589

In [20]:
dfMapEmissGdPop[
    (dfMapEmissGdPop['emiss_co2_2018_mtc'].isna()) | (dfMapEmissGdPop['pppgdp_2018'].isna()) | (dfMapEmissGdPop['pop_2018'].isna())
]

,Country ISO Code,Country Name,RICE 50+,Name within RICE,GCAM v7.1,emiss_co2_2018_mtc,pppgdp_2018,pop_2018
122,AND,Andorra,ris,ris,EU-15,NaN,4.152,0.076
129,BMU,Bermuda,rcam,rcam,Central America and Caribbean,0.345980,NaN,NaN
139,CUB,Cuba,rcam,rcam,Central America and Caribbean,47.894372,NaN,NaN
144,FRO,Faroe Islands,ris,ris,EU-15,0.050812,NaN,NaN
148,GRL,Greenland,ris,ris,EU-15,0.584499,NaN,NaN
155,IMN,Isle of Man,ris,ris,EU-15,NaN,NaN,NaN
157,XKX,Kosovo,ris,ris,Europe_Non_EU,NaN,NaN,NaN
162,LIE,Liechtenstein,ris,ris,European Free Trade Association,NaN,NaN,NaN
171,MCO,Monaco,ris,ris,EU-15,NaN,NaN,NaN
172,MNE,Montenegro,ris,ris,Europe_Non_EU,NaN,13.386,NaN
175,PSE,Palestinian Territories,meme,meme,Middle East,NaN,NaN,NaN
182,SMR,San Marino,ris,ris,EU-15,NaN,1.88,0.033
183,SRB,Serbia,ris,ris,Europe_Non_EU,NaN,123.717,6.983
190,SYR,Syria,meme,meme,Middle East,45.905388,NaN,NaN

In [21]:
dfMapEmissGdPop['emiss_co2_2018_mtc'] = dfMapEmissGdPop['emiss_co2_2018_mtc'].fillna(0)
dfMapEmissGdPop['pppgdp_2018'] = dfMapEmissGdPop['pppgdp_2018'].fillna(0)
dfMapEmissGdPop['pop_2018'] = dfMapEmissGdPop['pop_2018'].fillna(0)
dfMapEmissGdPop

,Country ISO Code,Country Name,RICE 50+,Name within RICE,GCAM v7.1,emiss_co2_2018_mtc,pppgdp_2018,pop_2018
0,AUS,Australia,aus,aus,Australia_NZ,597.774097,"1,290.18",25.146
1,NZL,New Zealand,osea,osea,Australia_NZ,87.715676,205.758,4.902
2,CHN,China,chn,chn,China,14296.571168,"22,368.20","1,405.41"
3,HKG,Hong Kong,rjan57,rjan57,China,50.490156,453.865,7.488
4,JPN,Japan,jpn,jpn,Japan,1265.994721,"5,344.06",126.495
...,...,...,...,...,...,...,...,...
194,TUV,Tuvalu,osea,osea,Southeast Asia,0.000000,0.045,0.011
195,UZB,Uzbekistan,oeu,oeu,Central Asia,213.167964,263.156,32.657
196,VUT,Vanuatu,osea,osea,Southeast Asia,0.693003,0.8,0.285
197,YEM,Yemen,golf57,golf57,Middle East,34.853295,62.366,30.415
198,TWN,Taiwan,chn,chn,Taiwan,317.943164,"1,180.13",23.589

In [22]:
dfMapEmissGdPop['pppgdp_2018'] = dfMapEmissGdPop['pppgdp_2018'].replace(",", '', regex=True).astype(float)
dfMapEmissGdPop['pop_2018'] = dfMapEmissGdPop['pop_2018'].replace(",", '', regex=True).astype(float)
dfMapEmissGdPop

,Country ISO Code,Country Name,RICE 50+,Name within RICE,GCAM v7.1,emiss_co2_2018_mtc,pppgdp_2018,pop_2018
0,AUS,Australia,aus,aus,Australia_NZ,597.774097,1290.180,25.146
1,NZL,New Zealand,osea,osea,Australia_NZ,87.715676,205.758,4.902
2,CHN,China,chn,chn,China,14296.571168,22368.200,1405.410
3,HKG,Hong Kong,rjan57,rjan57,China,50.490156,453.865,7.488
4,JPN,Japan,jpn,jpn,Japan,1265.994721,5344.060,126.495
...,...,...,...,...,...,...,...,...
194,TUV,Tuvalu,osea,osea,Southeast Asia,0.000000,0.045,0.011
195,UZB,Uzbekistan,oeu,oeu,Central Asia,213.167964,263.156,32.657
196,VUT,Vanuatu,osea,osea,Southeast Asia,0.693003,0.800,0.285
197,YEM,Yemen,golf57,golf57,Middle East,34.853295,62.366,30.415
198,TWN,Taiwan,chn,chn,Taiwan,317.943164,1180.130,23.589

In [23]:
# Group the DataFrame by the 'group_column' and calculate the sum for each group
group_sums = dfMapEmissGdPop.groupby('RICE 50+')['pppgdp_2018'].transform('sum')

# Calculate the share of each numeric value within its group
dfMapEmissGdPop['s_y_RICE'] = dfMapEmissGdPop['pppgdp_2018'] / group_sums

# Group the DataFrame by the 'group_column' and calculate the sum for each group
group_sums = dfMapEmissGdPop.groupby('RICE 50+')['pop_2018'].transform('sum')

# Calculate the share of each numeric value within its group
dfMapEmissGdPop['s_p_RICE'] = dfMapEmissGdPop['pop_2018'] / group_sums

# Group the DataFrame by the 'group_column' and calculate the sum for each group
group_sums = dfMapEmissGdPop.groupby('RICE 50+')['emiss_co2_2018_mtc'].transform('sum')

# Calculate the share of each numeric value within its group
dfMapEmissGdPop['s_e_RICE'] = dfMapEmissGdPop['emiss_co2_2018_mtc'] / group_sums

# Group the DataFrame by the 'group_column' and calculate the sum for each group
group_sums = dfMapEmissGdPop.groupby('GCAM v7.1')['pppgdp_2018'].transform('sum')

# Calculate the share of each numeric value within its group
dfMapEmissGdPop['s_y_GCAM'] = dfMapEmissGdPop['pppgdp_2018'] / group_sums

# Group the DataFrame by the 'group_column' and calculate the sum for each group
group_sums = dfMapEmissGdPop.groupby('GCAM v7.1')['pop_2018'].transform('sum')

# Calculate the share of each numeric value within its group
dfMapEmissGdPop['s_p_GCAM'] = dfMapEmissGdPop['pop_2018'] / group_sums

# Group the DataFrame by the 'group_column' and calculate the sum for each group
group_sums = dfMapEmissGdPop.groupby('GCAM v7.1')['emiss_co2_2018_mtc'].transform('sum')

# Calculate the share of each numeric value within its group
dfMapEmissGdPop['s_e_GCAM'] = dfMapEmissGdPop['emiss_co2_2018_mtc'] / group_sums

dfMapEmissGdPop

,Country ISO Code,Country Name,RICE 50+,Name within RICE,GCAM v7.1,emiss_co2_2018_mtc,pppgdp_2018,pop_2018,s_y_RICE,s_p_RICE,s_e_RICE,s_y_GCAM,s_p_GCAM,s_e_GCAM
0,AUS,Australia,aus,aus,Australia_NZ,597.774097,1290.180,25.146,1.000000,1.000000,1.000000,0.862456,0.836861,0.872039
1,NZL,New Zealand,osea,osea,Australia_NZ,87.715676,205.758,4.902,0.792242,0.260731,0.803019,0.137544,0.163139,0.127961
2,CHN,China,chn,chn,China,14296.571168,22368.200,1405.410,0.949885,0.983493,0.978245,0.976456,0.994231,0.996295
3,HKG,Hong Kong,rjan57,rjan57,China,50.490156,453.865,7.488,0.201458,0.051233,0.095923,0.019813,0.005297,0.003519
4,JPN,Japan,jpn,jpn,Japan,1265.994721,5344.060,126.495,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,TUV,Tuvalu,osea,osea,Southeast Asia,0.000000,0.045,0.011,0.000173,0.000585,0.000000,0.000009,0.000032,0.000000
195,UZB,Uzbekistan,oeu,oeu,Central Asia,213.167964,263.156,32.657,0.190614,0.322927,0.238274,0.219491,0.354209,0.252785
196,VUT,Vanuatu,osea,osea,Southeast Asia,0.693003,0.800,0.285,0.003080,0.015159,0.006344,0.000161,0.000826,0.000421
197,YEM,Yemen,golf57,golf57,Middle East,34.853295,62.366,30.415,0.012467,0.149481,0.012132,0.011166,0.132955,0.011344
198,TWN,Taiwan,chn,chn,Taiwan,317.943164,1180.130,23.589,0.050115,0.016507,0.021755,1.000000,1.000000,1.000000

In [24]:
dfMapEmissGdPop.to_excel('./output/shares.xlsx', index=False)