In [1]:
from pathlib import Path
import gcamreader
import os
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd
import plotly.io as pio

In [2]:
def to_Mt(row):
    val, unit = row['value'], row['Units']
    if unit == 'Tg':
        return val
    elif unit == 'Gg':
        return val * 1e-3
    elif unit == 'MTC':
        return val * (44.009 / 12.011)
    else:
        raise ValueError(f"Unknown unit: {unit}")

# AR5 100-yr GWP
GWP_AR5 = {
    'CO2':    1,
    'CH4': 28,  # Methane
    'CH4_AGR': 28,  # Methane from Agriculture
    'CH4_AWB': 28,  # Methane from Agricultural Waste Burning
    'N2O': 265,  # Nitrous Oxide
    'N2O_AGR': 265,  # Nitrous Oxide from Agriculture
    'N2O_AWB': 265,  # Nitrous Oxide from Agricultural Waste Burning
    'HFC125': 3500,
    'HFC134a':1430,
    'HFC143a':4470,
    'HFC23':  14800,
    'HFC32':  675,
    'HFC43':  1500,
    'HFC227ea':3220,
    'HFC236fa':9810,
    'SF6':    23500,
    'C2F6':   12200,
    'CF4':    6630,
}

In [3]:
proj_path = Path("/data/project/tae/gcam-core")
xml_path = proj_path / "input" / "gcamdata" / "xml"
db_path = proj_path / "output"

In [4]:
dbpath = "../output/"  # relative to current working directory
dbfile = "database_basexdb_korea_2035_sens"
# dbfile = "database_basexdb_test"
conn = gcamreader.LocalDBConn(dbpath, dbfile)
queries = gcamreader.parse_batch_query(os.path.join('..', 'output', 'queries','Main_queries.xml'))

Database scenarios: Enhanced-Ambition-Med

In [5]:
scenarios = list(conn.listScenariosInDB()['name'])
scenarios

['Enhanced-Ambition-Med']

In [7]:
scenarios=['Enhanced-Ambition-Med']

In [8]:
for i, q in enumerate(queries):
    print(i, q.title)

0 primary energy consumption by region (avg fossil efficiency)
1 primary energy consumption by region (direct equivalent)
2 primary energy consumption with CCS by region (direct equivalent)
3 resource production
4 resource production by tech and vintage
5 resource supply curves
6 regional primary energy prices
7 elec gen by region (incl CHP)
8 elec gen by subsector
9 elec gen by gen tech
10 elec gen by gen tech and cooling tech
11 elec gen by gen tech and cooling tech and vintage
12 elec gen by gen tech and cooling tech (new)
13 elec energy input by subsector
14 elec energy input by elec gen tech
15 elec energy input by elec gen tech and cooling tech
16 elec prices by sector
17 elec gen costs by subsector
18 elec gen costs by tech
19 elec gen costs by cooling tech
20 elec share-weights by subsector
21 elec share-weights by tech
22 elec share-weights by cooling tech
23 elec td inputs and outputs
24 cogeneration by region
25 elec consumption by demand sector
26 elec sector water withdrawals
27 elec sector water consumption
28 elec water withdrawals by gen tech
29 elec water consumption by gen tech
30 elec water withdrawals by gen tech and cooling tech
31 elec water consumption by gen tech and cooling tech
32 elec water withdrawals by gen tech and cooling tech (new)
33 elec water consumption by gen tech and cooling tech (new)
34 refined liquids production by region
35 refined liquids production by subsector
36 refined liquids production by tech
37 refined liquids production by tech and vintage
38 refined liquids production by tech (new)
39 refinery inputs by tech (energy and feedstocks)
40 refined liquids prices by sector
41 refined liquids costs by subsector
42 refined liquids costs by tech
43 refining and oil share-weights by subsector
44 refining share-weights by tech
45 hydrogen production by tech
46 hydrogen inputs by tech
47 hydrogen prices by sector
48 hydrogen costs by tech
49 hydrogen technology IO coefficients
50 hydrogen utilization by technology
51 hydrogen non-energy costs
52 hydrogen outputs by technology
53 hydrogen dispensing energy by primary fuel
54 gas production by tech
55 gas production share-weights by subsector
56 gas inputs by tech (energy and feedstocks)
57 gas pipeline inputs and outputs
58 gas prices by sector
59 gas costs by tech
60 gas consumption by sector
61 delivered gas energy by primary fuel
62 district heat production by subsector (fuel)
63 district heat energy inputs by subsector
64 total final energy by region
65 total final energy by aggregate sector
66 total final energy by sector
67 final energy consumption by fuel
68 final energy consumption by sector and fuel
69 final energy prices
70 building floorspace
71 building floorspace per capita
72 building commercial floorspace satiation impedance
73 building residential floorspace regional bias adder
74 building total final energy by region
75 building total final energy by service
76 building final energy by fuel
77 building final energy by service and fuel
78 building final energy by subsector
79 building final energy by tech
80 building final energy by tech and vintage
81 building final energy by tech (new)
82 building service output by service
83 building service output by subsector
84 building service output by tech
85 building service output by tech and vintage
86 building service output by tech (new)
87 building service density by energy service
88 building satiation impedance by energy service
89 building regional bias adder by energy service
90 building internal gain energy by service
91 total service cost per unit floorspace
92 building service costs
93 fuel prices to buildings
94 building share-weights by subsector
95 building share-weights by tech
96 industry total final energy by region
97 industry total final energy by service
98 industry final energy by fuel
99 industry final energy by service and fuel
100 industry final energy by tech and fuel
101 industry feedstocks by type
102 industry primary output by sector
103 industry cogeneration by fuel
104 fuel prices to industry
105 industry share-weights by subsector
106 industry water withdrawals and consumption
107 cement production by region
108 cement production by tech (conv and ccs)
109 cement production by tech and vintage
110 inputs to cement production
111 cement prices
112 ammonia production by region
113 ammonia production by tech
114 ammonia inputs by tech (energy and feedstocks)
115 ammonia and N fertilizer prices
116 ammonia domestic supply
117 ammonia exports (query USA region)
118 iron and steel production by region
119 iron and steel production by tech
120 iron and steel production by tech and vintage
121 iron and steel inputs by tech (energy and feedstocks)
122 iron and steel prices
123 traded iron and steel
124 regional iron and steel sources
125 chemical production by region
126 chemical inputs by tech (energy and feedstocks)
127 chemical prices
128 aluminum production by region
129 aluminum production by tech
130 aluminum production by tech and vintage
131 aluminum inputs by tech (energy and feedstocks)
132 aluminum prices
133 construction inputs (energy and feedstocks)
134 agricultural energy use
135 mining energy use
136 food processing production by region
137 food processing process heat production by tech
138 inputs to food processing
139 inputs to food processing (process heat separated)
140 food processing prices
141 paper production by region
142 inputs to paper production
143 paper prices
144 energy-for-water TFE
145 energy-for-water FE by fuel
146 energy-for-water FE by process and fuel
147 prices of energy-for-water processes
148 water flow volumes of EFW processes
149 nonrenewable groundwater pumping energy
150 transport total final energy by region
151 transport total final energy by service
152 transport final energy by fuel
153 transport final energy by mode and fuel
154 transport final energy by tech and fuel
155 transport final energy by tech and vintage
156 transport final energy by tech (new)
157 transport service output by service
158 transport service output by mode
159 transport service output by tech
160 transport service output by tech and vintage
161 transport service output by tech (new)
162 transport load factors
163 fuel prices to transport
164 costs of transport services
165 costs of transport modes
166 costs of transport techs
167 transport tech non-energy cost
168 LDV energy by primary fuel
169 transport subsector share-weights
170 transport tech share-weights
171 transport speeds
172 building final energy by tech
173 building service output by tech
174 building floorspace
175 industry final energy by service and fuel
176 transport final energy by tech and fuel
177 transport final energy by tech (new)
178 transport service output by tech
179 transport service output by tech (new)
180 detailed land allocation
181 detailed historical land allocation
182 land allocation by crop
183 aggregated land allocation
184 aggregated historical land allocation
185 land allocation in a specified land use region
186 land allocation by crop and water source
187 LUC emissions by region
188 LUC emissions by LUT
189 LUC emissions by LUT in a specified land use region
190 vegetative carbon stock by region
191 profit rate
192 profit rate in a specified land use region
193 land leaf shares
194 land leaf shares in a specified land use region
195 ag production by crop type
196 ag production by subsector (land use region)
197 ag production in a specified land use region
198 ag production by tech
199 ag tech variable cost
200 ag tech yield
201 ag tech yield in a specified land region
202 ag commodity prices
203 ag tech implied subsidy
204 irrigation water withdrawals by region
205 irrigation water withdrawals by crop type
206 irrigation water withdrawals by crop type and land region
207 irrigation water withdrawals by ag tech
208 irrigation water consumption by region
209 irrigation water consumption by crop type
210 irrigation water consumption by crop type and land region
211 irrigation water consumption by ag tech
212 biophysical water demand by region
213 biophysical water demand by crop type
214 biophysical water demand by crop type and land region
215 biophysical water demand by ag tech
216 fertilizer consumption by region
217 fertilizer consumption by crop type
218 fertilizer consumption by ag tech
219 fertilizer-crop input-output coefficients
220 purpose-grown biomass production
221 residue biomass production
222 MSW production
223 regional biomass consumption
224 meat and dairy production by type
225 meat and dairy production by tech
226 meat and dairy prices
227 meat and dairy subsector share-weights
228 meat and dairy tech share-weights
229 meat and dairy subsector costs
230 meat and dairy tech costs
231 water consumption by meat and dairy production
232 feed consumption by region
233 feed consumption by meat and dairy tech
234 feed sources
235 feed prices
236 feed subsector share-weights
237 food consumption by type (general)
238 food consumption by type (specific)
239 demand balances by crop commodity
240 demand balances by meat and dairy commodity
241 food demand prices
242 food demand
243 food demand per capita
244 food demand regional bias
245 ag import vs. domestic supply (Regional Armington competition)
246 ag export to the world center (USA) (Intl. Armington competition)
247 ag import vs. domestic prices
248 ag export prices (at world center USA)
249 import vs. domestic share-weights (Armington regional taste)
250 international competition share-weights (Armington intl. taste)
251 ag total prices (weighted average b/t domestic and imported prices)
252 opening stocks (supply from carryover)
253 closing stocks (before loss/adjustments)
254 closing stocks (after loss/adjustments; carried over)
255 current supply (current or regional consumption)
256 ag regional prices (current consumer prices)
257 agricultural storage share-weights
258 storage cost
259 expected price
260 CO2 emissions by region
261 CO2 emissions by sector (excluding resource production)
262 CO2 emissions by sector (no bio) (excluding resource production)
263 CO2 emissions by assigned sector (no bio) (excluding resource production)
264 CO2 emissions by subsector (excluding resource production)
265 CO2 emissions by tech (excluding resource production)
266 CO2 emissions by resource production
267 CO2 sequestration by sector
268 CO2 sequestration by tech
269 nonCO2 emissions by region
270 nonCO2 emissions by sector (excluding resource production)
271 nonCO2 emissions by resource production
272 nonCO2 emissions by subsector (excluding resource production)
273 nonCO2 emissions by tech (excluding resource production)
274 specific nonCO2 emissions by region
275 specific nonCO2 emissions by sector (excluding resource production)
276 specific nonCO2 emissions by resource production
277 specific nonCO2 emissions by subsector (excluding resource production)
278 specific nonCO2 emissions by tech (excluding resource production)
279 CO2 concentrations
280 total climate forcing
281 global mean temperature
282 net terrestrial C uptake
283 population by region
284 GDP MER by region
285 GDP per capita MER by region
286 GDP per capita PPP by region
287 subregional population
288 subregional income
289 National Account
290 Social Accounting Matrix
291 Tracking accounts by tech
292 Capital investment demands by tech
293 Capital investment demands by resource
294 CO2 prices
295 policy cost by period
296 undiscounted policy cost
297 discounted policy cost
298 regional CO2 MAC curves by period
299 water withdrawals by region
300 water withdrawals by water mapping source
301 water withdrawals by sector
302 water withdrawals by subsector
303 water withdrawals by tech
304 water consumption by region
305 water consumption by water mapping source
306 water consumption by sector
307 water consumption by subsector
308 water consumption by tech
309 Basin level available runoff
310 Water withdrawals by water source (runoff vs. groundwater)
311 Water Withdrawals by Basin (Runoff)
312 Water Withdrawals by Basin (Groundwater)
313 Cumulative groundwater extraction
314 prices of all markets
315 supply of all markets
316 demand of all markets
317 price of a specific market
318 supply of a specific market
319 prices by sector
320 costs by subsector
321 costs by tech
322 costs by tech and input
323 inputs by sector
324 inputs by subsector
325 inputs by tech
326 outputs by sector
327 outputs by subsector
328 outputs by tech
329 input-output coefficients by tech
330 primary energy consumption by region (direct equivalent)
331 industry water withdrawals and consumption
332 elec gen by region (no CHP)
333 elec gen by subsector
334 elec gen by gen tech (cogen only)
335 elec gen by gen tech and cooling tech (incl cogen)
336 elec energy input by subsector
337 elec energy input by elec gen tech
338 elec prices by sector
339 elec gen costs by subsector
340 elec gen costs by tech
341 elec share-weights by subsector
342 elec share-weights by gen tech
343 elec share-weights by cooling tech
344 elec water withdrawals by gen tech and cooling tech
345 elec water consumption by gen tech and cooling tech
346 refined liquids production by region
347 refined liquids production by subsector
348 refined liquids production by tech
349 refined liquids production by tech and vintage
350 refined liquids production by tech (new)
351 refinery inputs by tech (energy and feedstocks)
352 refined liquids prices by sector
353 refined liquids costs by subsector
354 refined liquids costs by tech
355 refining and oil share-weights by subsector
356 refining share-weights by tech
357 total final energy by aggregate sector
358 water withdrawals by state, sector, basin
359 water withdrawals by state, sector, basin (includes desal)
360 water consumption by state, sector, basin
361 water consumption by state, sector, basin (includes desal)
362 CO2 emissions by tech (nested subsector) (excluding resource production)
363 CO2 sequestration by tech (nested subsector)

In [11]:
i = 120
q = queries[i]
title = q.title
print(title)
df = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
df['scenario'] = df['scenario'].str.split(',').str[0]
# df.groupby(['scenario', 'Year'])['value'].sum()
df

iron and steel production by tech and vintage

,Units,scenario,region,sector,subsector,technology,output,Year,value
0,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR CCS,year=2025",iron and steel,2025,0.473095
1,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR CCS,year=2025",iron and steel,2030,0.386728
2,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR CCS,year=2025",iron and steel,2035,0.236503
3,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR CCS,year=2030",iron and steel,2030,5.924920
4,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR CCS,year=2030",iron and steel,2035,4.843150
...,...,...,...,...,...,...,...,...,...
73,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,EAF with scrap,"EAF with scrap,year=2025",iron and steel,2030,6.548490
74,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,EAF with scrap,"EAF with scrap,year=2025",iron and steel,2035,4.004800
75,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,EAF with scrap,"EAF with scrap,year=2030",iron and steel,2030,12.401400
76,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,EAF with scrap,"EAF with scrap,year=2030",iron and steel,2035,10.138700
77,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,EAF with scrap,"EAF with scrap,year=2035",iron and steel,2035,13.242000

In [12]:
df[(df['subsector']=='BLASTFUR')]

,Units,scenario,region,sector,subsector,technology,output,Year,value
0,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR CCS,year=2025",iron and steel,2025,0.473095
1,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR CCS,year=2025",iron and steel,2030,0.386728
2,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR CCS,year=2025",iron and steel,2035,0.236503
3,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR CCS,year=2030",iron and steel,2030,5.924920
4,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR CCS,year=2030",iron and steel,2035,4.843150
5,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR CCS,year=2035",iron and steel,2035,6.869380
6,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR with hydrogen,year=2025",iron and steel,2025,0.491862
7,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR with hydrogen,year=2025",iron and steel,2030,0.402108
8,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR with hydrogen,year=2025",iron and steel,2035,0.245907
9,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR with hydrogen,year=2030",iron and steel,2030,3.214730
10,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR with hydrogen,year=2030",iron and steel,2035,2.628020
11,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR with hydrogen,year=2035",iron and steel,2035,2.732240
12,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=1975",iron and steel,1975,0.665514
13,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=1990",iron and steel,1990,13.226000
14,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2005",iron and steel,2005,26.767200
15,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2010",iron and steel,2010,34.108100
16,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2015",iron and steel,2015,48.479100
17,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2015",iron and steel,2020,39.635100
18,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2015",iron and steel,2025,24.239500
19,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2015",iron and steel,2030,8.843790
20,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2020",iron and steel,2020,9.483540
21,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2020",iron and steel,2025,7.753480
22,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2020",iron and steel,2030,4.741750
23,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2020",iron and steel,2035,1.730030
24,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2025",iron and steel,2025,13.629000
25,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2025",iron and steel,2030,11.142500
26,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"BLASTFUR,year=2025",iron and steel,2035,6.814340
27,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"Biomass-based,year=2025",iron and steel,2025,0.632433
28,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"Biomass-based,year=2025",iron and steel,2030,0.517035
29,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"Biomass-based,year=2025",iron and steel,2035,0.316188
30,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"Biomass-based,year=2030",iron and steel,2030,3.616780
31,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"Biomass-based,year=2030",iron and steel,2035,2.956720
32,Mt,Enhanced-Ambition-Med,South Korea,iron and steel,BLASTFUR,"Biomass-based,year=2035",iron and steel,2035,2.839420

In [127]:
def cat_tech(tech):

    if tech == 'BLASTFUR':
        return 'BF'
    elif tech == 'BLASTFUR CCS':
        return 'BF-CCS'
    elif tech == 'BLASTFUR with hydrogen':
        return 'BF-H2'
    elif tech == 'Biomass-based':
        return 'BF-Biomass'
    elif tech == 'EAF with DRI':
        return 'DRI-EAF'
    elif tech == 'EAF with DRI CCS':
        return 'DRI-EAF-CCS'
    elif tech == 'Hydrogen-based DRI':
        return 'DRI-EAF-H2'
    elif tech == 'EAF with scrap':
        return 'EAF-scrap'

In [128]:
df['tech'] = df['technology'].apply(cat_tech)

In [129]:
stack_order = [
    'BF', 'BF-CCS', 'BF-H2', 'BF-Biomass', 'EAF-scrap', 'DRI-EAF', 'DRI-EAF-CCS', 'DRI-EAF-H2', 
]

In [130]:
df['tech'] = pd.Categorical(df['tech'], categories=stack_order, ordered=True)
df = df.sort_values(by=['Year', 'tech'])
df['tech'].unique()

['BF', 'EAF-scrap', 'DRI-EAF', 'BF-CCS', 'BF-H2', 'BF-Biomass', 'DRI-EAF-CCS', 'DRI-EAF-H2']
Categories (8, object): ['BF' < 'BF-CCS' < 'BF-H2' < 'BF-Biomass' < 'EAF-scrap' < 'DRI-EAF' < 'DRI-EAF-CCS' < 'DRI-EAF-H2']

In [131]:
dfAgg1 = df[(df['Year'] >= 2005) & (df['scenario'] == scenarios[0])].groupby(['Year', 'tech'])['value'].sum().reset_index()
fig1 = px.bar(dfAgg1, x="Year", y="value", color="tech", title="Ref.")
dfAgg2 = df[(df['Year'] >= 2005) & (df['scenario'] == scenarios[1])].groupby(['Year', 'tech'])['value'].sum().reset_index()
fig2 = px.bar(dfAgg2, x="Year", y="value", color="tech", title="Enhanced Ambition")
# fig1

/tmp/ipykernel_12975/2270479744.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

/tmp/ipykernel_12975/2270479744.py:3: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [132]:
# ---- Colour & hatch (“pattern”) settings ------------------------
fuel_colors = {
    "BF"           : "#000000",   # solid black
    "BF-CCS"       : "grey",   # same black, but we’ll add a hatch
    "BF-H2"            : "#E4EAED",   # bright blue
    "EAF-scrap"        : "#492681",   # lighter cyan-blue
    "BF-Biomass"        : "#099B43",   # medium green
    "DRI-EAF"    : "#0057B5",   # deep blue
    "DRI-EAF-H2"       : "#FED30B",   # golden yellow
    "DRI-EAF-CCS"            : "#4DDADC",   # white base; will rely on hatch only
}

# optional: hatch / pattern overlay for the categories that are
# drawn with diagonal stripes in the figure
fuel_patterns = {
    "BF-CCS": "/",   # forward-slash hatch
    "DRI-EAF-CCS" : "/",   # same
    "DRI-EAF-H2"     : "\\",  # back-slash hatch
}

# Example of applying in Plotly
import plotly.graph_objects as go

def bar_for(fuel, x, y):
    return go.Bar(
        name   = fuel,
        x      = x,
        y      = y,
        marker = dict(
            color   = fuel_colors[fuel],
            pattern = dict(shape = fuel_patterns.get(fuel, ""))
        )
    )

In [133]:
years = list(range(2005, 2051, 5))

# Create clean figure with 1 subplot
fig = make_subplots(
    rows=1, cols=2,
    shared_yaxes=True,
    shared_xaxes=True,
    # specs=[[{"secondary_y": True}, {"secondary_y": True}]],
    subplot_titles=("Current Policies", "Enhanced Ambition")
)

# Add traces from fig1
for tr in fig1.data:
    tr.showlegend = False  # Show legend

    # Apply color and pattern if available
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=1)
for tr in fig2.data:
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=2, secondary_y=False)


# Layout settings
fig.update_layout(
    barmode='stack',
    plot_bgcolor='rgba(0,0,0,0)',
    width=800,
    height=700,
    # title=dict(
    #     text="<b>Panel A</b>",
    #     font=dict(size=28),
    #     x=0.5
    # ),
    yaxis=dict(
        title="Mt",
        range=[0, 89],
        showgrid=True,
        gridcolor='lightgray',
        title_font=dict(size=24),
        tickfont=dict(size=21)
    ),
    yaxis2=dict(
        range=[0, 89],
        showgrid=True,
        gridcolor='lightgray',
        title_font=dict(size=24),
        tickfont=dict(size=21)
    ),
    xaxis=dict(
        # title="Year",
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        title_font=dict(size=24),
        tickfont=dict(size=21)
    ),
    xaxis2=dict(
        # title="Year",
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        title_font=dict(size=24),
        tickfont=dict(size=21)
    ),
    legend=dict(
        traceorder="reversed",
        font=dict(size=18),
        x=1.02, y=1,
        borderwidth=0
    )
)

# Apply font size to annotations (if any)
fig.update_annotations(font=dict(size=21))
pio.write_image(fig, "./fig/ironsteel_production.png", width=800, height=700, scale=2)

# Show figure
fig.show()

In [134]:
i = 100
q = queries[i]
title = q.title
print(title)
df = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
df['scenario'] = df['scenario'].str.split(',').str[0]
df

industry final energy by tech and fuel

,Units,scenario,region,sector,subsector,technology,input,Year,value
0,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2025,0.000057
1,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2030,0.000278
2,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2035,0.000585
3,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2025,0.000054
4,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2030,0.000204
...,...,...,...,...,...,...,...,...,...
1245,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2015,0.002158
1246,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2020,0.002360
1247,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2025,0.002459
1248,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2030,0.003219
1249,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2035,0.005094

In [135]:
def cat_fuel(row):
    fuel = row['input']
    tech = row['technology']
    if tech in ['gas CCS', 'biomass CCS', 'coal CCS', 'refined liquids CCS']:
        return tech
    # elif tech in ['hightemp DAC NG', 'hightemp DAC elec', 'lowtemp DAC heatpump']:
    #     return 'DAC'
    elif tech == 'electricity with solar':
        return 'electricity'
    elif tech == 'gas with solar':
        return 'gas' 
    elif fuel in ['H2 wholesale dispensing', 'H2 wholesale delivery', 'H2 industrial']:
        return 'hydrogen'
    elif fuel == 'elect_td_ind':
        return 'electricity'
    elif fuel in ['refined liquids industrial']:
        return 'refined liquids'
    elif fuel in ['delivered biomass', 'regional woodpulp for energy']:
        return 'biomass'
    elif fuel in ['wholesale gas']:
        return 'gas'
    elif fuel in ['delivered coal']:
        return 'coal'
    else:
        print(fuel, tech)
        return 'others'

In [136]:
df['Units'].unique()

array(['EJ'], dtype=object)

In [137]:
df['input'].unique()

array(['elect_td_ind', 'H2 wholesale dispensing',
       'refined liquids industrial', 'delivered biomass', 'wholesale gas',
       'H2 wholesale delivery', 'H2 industrial', 'delivered coal',
       'global solar resource', 'regional woodpulp for energy'],
      dtype=object)

In [138]:
df['fuel'] = df.apply(cat_fuel, axis=1)
df.head()

,Units,scenario,region,sector,subsector,technology,input,Year,value,fuel
0,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2025,0.000057,electricity
1,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2030,0.000278,electricity
2,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2035,0.000585,electricity
3,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2025,0.000054,hydrogen
4,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2030,0.000204,hydrogen

In [139]:
dfFig = df[(df['Year'] >= 2005)].groupby(['scenario', 'Year', 'fuel'])['value'].sum().reset_index()
dfFig.head()

         scenario  Year             fuel     value
0  Current-Policy  2005          biomass  0.107670
1  Current-Policy  2005             coal  0.823345
2  Current-Policy  2005      electricity  0.671997
3  Current-Policy  2005              gas  0.213206
4  Current-Policy  2005  refined liquids  1.797392

In [140]:
dfFig['value'] *= 23.8846

In [141]:
# dfFig['fuel'] = dfFig['fuel'].apply(lambda fuel: fuel.capitalize())
dfFig['fuel'].unique()

array(['biomass', 'coal', 'electricity', 'gas', 'refined liquids',
       'biomass CCS', 'coal CCS', 'gas CCS', 'hydrogen',
       'refined liquids CCS'], dtype=object)

In [142]:
stack_order = [
    #'DAC', 
    'hydrogen', 'electricity', 'biomass CCS', 'biomass', 'gas CCS', 'gas', 'coal CCS', 'coal', 'refined liquids CCS', 'refined liquids'
]

In [143]:
dfFig['fuel'] = pd.Categorical(dfFig['fuel'], categories=stack_order, ordered=True)
dfFig = dfFig.sort_values(by=['Year', 'fuel'])
dfFig['fuel'].unique()

['electricity', 'biomass', 'gas', 'coal', 'refined liquids', 'hydrogen', 'biomass CCS', 'gas CCS', 'coal CCS', 'refined liquids CCS']
Categories (10, object): ['hydrogen' < 'electricity' < 'biomass CCS' < 'biomass' ... 'coal CCS' < 'coal' < 'refined liquids CCS' < 'refined liquids']

In [144]:
dfAgg1 = dfFig[(dfFig['scenario'] == scenarios[0])]
fig1 = px.bar(dfAgg1, x="Year", y="value", color="fuel", title="Current Policy")
dfAgg2 = dfFig[(dfFig['scenario'] == scenarios[1])]
fig2 = px.bar(dfAgg2, x="Year", y="value", color="fuel", title="Enhanced Ambition")

In [145]:
# ---- Colour & hatch (“pattern”) settings ------------------------
fuel_colors = {
    "refined liquids CCS": "#FFB785",    # peach
    "refined liquids" : "#EF0C0C",   # vivid red
    "coal"           : "#000000",   # solid black
    "coal CCS"       : "#000000",   # same black, but we’ll add a hatch
    "gas"            : "#0186E0",   # bright blue
    "gas CCS"        : "#33A8E2",   # lighter cyan-blue
    "biomass"        : "#099B43",   # medium green
    "electricity"    : "#0057B5",   # deep blue
    "hydrogen"       : "#FED30B",   # golden yellow
    "DAC"            : "#FFFFFF",   # white base; will rely on hatch only
}

# optional: hatch / pattern overlay for the categories that are
# drawn with diagonal stripes in the figure
fuel_patterns = {
    "coal CCS": "/",   # forward-slash hatch
    "gas CCS" : "/",   # same
    "refined liquids CCS": "/",
    "biomass CCS": "/",
    "DAC"     : "\\",  # back-slash hatch
}

# Example of applying in Plotly
import plotly.graph_objects as go

def bar_for(fuel, x, y):
    return go.Bar(
        name   = fuel,
        x      = x,
        y      = y,
        marker = dict(
            color   = fuel_colors[fuel],
            pattern = dict(shape = fuel_patterns.get(fuel, ""))
        )
    )

In [146]:
years = list(range(2005, 2036, 5))

fig = make_subplots(
    rows=1, cols=2,
    shared_yaxes=True,
    shared_xaxes=True,
    # specs=[[{"secondary_y": True}, {"secondary_y": True}]],
    subplot_titles=("Current Policies", "Enhanced Ambition")
)

# Add traces from fig1
for tr in fig1.data:
    tr.showlegend = False # Show legend

    # Apply color and pattern if available
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=1)

for tr in fig2.data:
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=2, secondary_y=False)

# Layout settings
fig.update_layout(
    barmode='stack',
    plot_bgcolor='rgba(0,0,0,0)',
    width=800,
    height=700,
    # title=dict(
    #     text="<b>Panel A</b>",
    #     font=dict(size=24),
    #     x=0.5
    # ),
    yaxis=dict(
        title="mil. toe",
        range=[0, 150],
        showgrid=True,
        gridcolor='lightgray',
        title_font=dict(size=24),
        tickfont=dict(size=21)
    ),
    xaxis=dict(
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        tickfont=dict(size=21)
    ),
    yaxis2=dict(
        range=[0, 150],
        showgrid=True,
        gridcolor='lightgray',
        tickfont=dict(size=21)
    ),
    xaxis2=dict(
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        tickfont=dict(size=21)
    ),
    legend=dict(
        traceorder="reversed",
        font=dict(size=18),
        x=1.02, y=1,
        borderwidth=0
    )
)

# Apply font size to annotations (if any)
fig.update_annotations(font=dict(size=21))
pio.write_image(fig, "./fig/industry_energy_type.png", width=800, height=700, scale=2)

# Show figure
fig.show()

In [147]:
df['sector'].unique()

array(['agricultural energy use', 'ammonia', 'cement',
       'chemical energy use', 'chemical feedstocks',
       'construction energy use', 'construction feedstocks',
       'food processing', 'iron and steel', 'mining energy use',
       'other industrial energy use', 'other industrial feedstocks',
       'paper', 'process heat cement', 'process heat food processing',
       'process heat paper', 'waste biomass for paper', 'CO2 removal',
       'process heat dac'], dtype=object)

In [179]:
i = 100
q = queries[i]
title = q.title
print(title)
df = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
df['scenario'] = df['scenario'].str.split(',').str[0]
df

industry final energy by tech and fuel

,Units,scenario,region,sector,subsector,technology,input,Year,value
0,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2025,0.000057
1,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2030,0.000278
2,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2035,0.000585
3,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2025,0.000054
4,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2030,0.000204
...,...,...,...,...,...,...,...,...,...
1245,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2015,0.002158
1246,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2020,0.002360
1247,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2025,0.002459
1248,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2030,0.003219
1249,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2035,0.005094

In [180]:
def cat_sec(sec):
    if sec in ['agricultural energy use']:
        return "Agriculture"
    elif sec in ['ammonia', 'chemical energy use', 'chemical feedstocks']:
        return "Chemical"
    elif sec in ['cement', 'process heat cement']:
        return "Cement"
    elif sec in ['construction energy use', 'construction feedstocks']:
        return 'Construction'
    elif sec in ['food processing', 'process heat food processing']:
        return "Food"
    elif sec in ['iron and steel']:
        return "Iron and Steel"
    elif sec in ['mining energy use']:
        return 'Mining'
    elif sec in ['paper', 'process heat paper', 'waste biomass for paper']:
        return "Paper"
    elif sec in ['CO2 removal', 'process heat dac']:
        return "DAC"
    elif sec in ['other industrial energy use', 'other industrial feedstocks']:
        return 'Other Industry'
    else:
        print(sec)
        return 'others'

In [181]:
df['ind'] = df['sector'].apply(cat_sec)
df.head()

,Units,scenario,region,sector,subsector,technology,input,Year,value,ind
0,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2025,0.000057,Agriculture
1,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2030,0.000278,Agriculture
2,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2035,0.000585,Agriculture
3,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2025,0.000054,Agriculture
4,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2030,0.000204,Agriculture

In [182]:
dfFig = df[(df['Year'] >= 2015)].groupby(['scenario', 'Year', 'ind'])['value'].sum().reset_index()
dfFig.head()

         scenario  Year           ind     value
0  Current-Policy  2015   Agriculture  0.064028
1  Current-Policy  2015        Cement  0.195241
2  Current-Policy  2015      Chemical  2.177936
3  Current-Policy  2015  Construction  0.085269
4  Current-Policy  2015          Food  0.074013

In [183]:
dfFig['value'] *= 23.8846

In [184]:
# dfFig['fuel'] = dfFig['fuel'].apply(lambda fuel: fuel.capitalize())
dfFig['ind'].unique()

array(['Agriculture', 'Cement', 'Chemical', 'Construction', 'Food',
       'Iron and Steel', 'Mining', 'Other Industry', 'Paper', 'DAC'],
      dtype=object)

In [185]:
stack_order = [
    'DAC', 'Iron and Steel', 'Chemical', 'Cement', 'Construction', 'Food', 'Paper', 'Mining', 'Agriculture', 'Other Industry'
]

In [186]:
dfFig['ind'] = pd.Categorical(dfFig['ind'], categories=stack_order, ordered=True)
dfFig = dfFig.sort_values(by=['Year', 'ind'])
dfFig['ind'].unique()

['Iron and Steel', 'Chemical', 'Cement', 'Construction', 'Food', 'Paper', 'Mining', 'Agriculture', 'Other Industry', 'DAC']
Categories (10, object): ['DAC' < 'Iron and Steel' < 'Chemical' < 'Cement' ... 'Paper' < 'Mining' < 'Agriculture' < 'Other Industry']

In [187]:
dfAgg1 = dfFig[(dfFig['scenario'] == scenarios[0])]
fig1 = px.bar(dfAgg1, x="Year", y="value", color="ind", title="Current Policy")
dfAgg2 = dfFig[(dfFig['scenario'] == scenarios[1])]
fig2 = px.bar(dfAgg2, x="Year", y="value", color="ind", title="Enhanced Ambition")

In [188]:
stack_order

['DAC',
 'Iron and Steel',
 'Chemical',
 'Cement',
 'Construction',
 'Food',
 'Paper',
 'Mining',
 'Agriculture',
 'Other Industry']

In [189]:
# ---- Colour & hatch (“pattern”) settings ------------------------
fuel_colors = {    
    "Other Industry" : "#0186E0",   # golden yellow
    "Agriculture"    : "rgb(166,86,40)",   # lighter cyan-blue
    "Mining"         : "orange",   # medium green
    "Paper"          : "green",   # white base; will rely on hatch only
    "Food"           : "#0057B5",   # deep blue
    "Construction"   : "#FED30B",   # bright blue
    "Cement": "grey",    # peach
    "Chemical" : "#EF0C0C",   # vivid red
    "Iron and Steel" : "#000000",   # solid black
    "DAC"            : "#FFFFFF",
}

# optional: hatch / pattern overlay for the categories that are
# drawn with diagonal stripes in the figure
fuel_patterns = {
    "DAC"     : "\\",  # back-slash hatch
}

# Example of applying in Plotly
import plotly.graph_objects as go

def bar_for(fuel, x, y):
    return go.Bar(
        name   = fuel,
        x      = x,
        y      = y,
        marker = dict(
            color   = fuel_colors[fuel],
            pattern = dict(shape = fuel_patterns.get(fuel, ""))
        )
    )

In [190]:
years = list(range(2015, 2051, 5))

fig = make_subplots(
    rows=1, cols=2,
    shared_yaxes=True,
    shared_xaxes=True,
    subplot_titles=("Current Policies", "Enhanced Ambition")
)

for tr in fig1.data:  # ⬅️ reverse stacking order
    tr.showlegend = False
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)
    fig.add_trace(tr, row=1, col=1)

for tr in fig2.data:
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=2, secondary_y=False)


# Layout settings
fig.update_layout(
    barmode='stack',
    plot_bgcolor='rgba(0,0,0,0)',
    width=650,
    height=680,
    # title=dict(
    #     text="<b>Panel B</b>",
    #     font=dict(size=24),
    #     x=0.5
    # ),
    yaxis=dict(
        title="mil. toe",
        range=[0, 150],
        showgrid=True,
        gridcolor='lightgray',
        title_font=dict(size=24),
        tickfont=dict(size=21)
    ),
    xaxis=dict(
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        tickfont=dict(size=21)
    ),
    yaxis2=dict(
        range=[0, 150],
        showgrid=True,
        gridcolor='lightgray',
        tickfont=dict(size=21)
    ),
    xaxis2=dict(
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        tickfont=dict(size=21)
    ),
    legend=dict(
        traceorder="reversed",
        font=dict(size=18),
        x=1.02, y=1,
        borderwidth=0
    )
)

# Apply font size to annotations (if any)
fig.update_annotations(font=dict(size=21))
pio.write_image(fig, "./fig/industry_energy_sector.png", width=650, height=680, scale=2)

# Show figure
fig.show()

In [191]:
i = 100
q = queries[i]
title = q.title
print(title)
df = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
df['scenario'] = df['scenario'].str.split(',').str[0]
df

industry final energy by tech and fuel

,Units,scenario,region,sector,subsector,technology,input,Year,value
0,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2025,0.000057
1,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2030,0.000278
2,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2035,0.000585
3,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2025,0.000054
4,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2030,0.000204
...,...,...,...,...,...,...,...,...,...
1245,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2015,0.002158
1246,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2020,0.002360
1247,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2025,0.002459
1248,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2030,0.003219
1249,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2035,0.005094

In [192]:
def cat_fuel(row):
    fuel = row['input']
    tech = row['technology']
    if tech in ['gas CCS', 'biomass CCS', 'coal CCS', 'refined liquids CCS']:
        return tech
    elif tech == 'electricity with solar':
        return 'electricity'
    elif tech == 'gas with solar':
        return 'gas' 
    elif fuel in ['H2 wholesale dispensing', 'H2 wholesale delivery', 'H2 industrial']:
        return 'hydrogen'
    elif fuel == 'elect_td_ind':
        return 'electricity'
    elif fuel in ['refined liquids industrial']:
        return 'refined liquids'
    elif fuel in ['delivered biomass', 'regional woodpulp for energy']:
        return 'biomass'
    elif fuel in ['wholesale gas']:
        return 'gas'
    elif fuel in ['delivered coal']:
        return 'coal'
    else:
        print(fuel, tech)
        return 'others'

In [193]:
df['Units'].unique()

array(['EJ'], dtype=object)

In [194]:
df['input'].unique()

array(['elect_td_ind', 'H2 wholesale dispensing',
       'refined liquids industrial', 'delivered biomass', 'wholesale gas',
       'H2 wholesale delivery', 'H2 industrial', 'delivered coal',
       'global solar resource', 'regional woodpulp for energy'],
      dtype=object)

In [195]:
df['fuel'] = df.apply(cat_fuel, axis=1)
df['ind'] = df['sector'].apply(cat_sec)
df.head()

,Units,scenario,region,sector,subsector,technology,input,Year,value,fuel,ind
0,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2025,0.000057,electricity,Agriculture
1,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2030,0.000278,electricity,Agriculture
2,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2035,0.000585,electricity,Agriculture
3,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2025,0.000054,hydrogen,Agriculture
4,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2030,0.000204,hydrogen,Agriculture

In [196]:
dfFig = df[(df['Year'] >= 2015) & (df['ind'] == 'Iron and Steel')].groupby(['scenario', 'Year', 'fuel'])['value'].sum().reset_index()
dfFig.head()

         scenario  Year             fuel     value
0  Current-Policy  2015             coal  0.853610
1  Current-Policy  2015      electricity  0.195444
2  Current-Policy  2015              gas  0.063964
3  Current-Policy  2015  refined liquids  0.004185
4  Current-Policy  2020             coal  0.848227

In [197]:
dfFig['value'] *= 23.8846

In [198]:
# dfFig['fuel'] = dfFig['fuel'].apply(lambda fuel: fuel.capitalize())
dfFig['fuel'].unique()

array(['coal', 'electricity', 'gas', 'refined liquids', 'biomass',
       'hydrogen'], dtype=object)

In [199]:
stack_order = [
    'hydrogen', 'electricity', 'biomass CCS', 'biomass', 'gas CCS', 'gas', 'coal CCS', 'coal', 'refined liquids CCS', 'refined liquids'
]

In [200]:
dfFig['fuel'] = pd.Categorical(dfFig['fuel'], categories=stack_order, ordered=True)
dfFig = dfFig.sort_values(by=['Year', 'fuel'])
dfFig['fuel'].unique()

['electricity', 'gas', 'coal', 'refined liquids', 'hydrogen', 'biomass']
Categories (10, object): ['hydrogen' < 'electricity' < 'biomass CCS' < 'biomass' ... 'coal CCS' < 'coal' < 'refined liquids CCS' < 'refined liquids']

In [201]:
dfAgg1 = dfFig[(dfFig['scenario'] == scenarios[0])]
fig1 = px.bar(dfAgg1, x="Year", y="value", color="fuel", title="Current Policy")
dfAgg2 = dfFig[(dfFig['scenario'] == scenarios[1])]
fig2 = px.bar(dfAgg2, x="Year", y="value", color="fuel", title="Enhanced Ambition")

In [202]:
# ---- Colour & hatch (“pattern”) settings ------------------------
fuel_colors = {
    "refined liquids CCS": "#FFB785",    # peach
    "refined liquids" : "#EF0C0C",   # vivid red
    "coal"           : "#000000",   # solid black
    "coal CCS"       : "#000000",   # same black, but we’ll add a hatch
    "gas"            : "#0186E0",   # bright blue
    "gas CCS"        : "#33A8E2",   # lighter cyan-blue
    "biomass"        : "#099B43",   # medium green
    "electricity"    : "#0057B5",   # deep blue
    "hydrogen"       : "#FED30B",   # golden yellow
    "DAC"            : "#FFFFFF",   # white base; will rely on hatch only
}

# optional: hatch / pattern overlay for the categories that are
# drawn with diagonal stripes in the figure
fuel_patterns = {
    "coal CCS": "/",   # forward-slash hatch
    "gas CCS" : "/",   # same
    "refined liquids CCS": "/",
    "biomass CCS": "/",
    "DAC"     : "\\",  # back-slash hatch
}

# Example of applying in Plotly
import plotly.graph_objects as go

def bar_for(fuel, x, y):
    return go.Bar(
        name   = fuel,
        x      = x,
        y      = y,
        marker = dict(
            color   = fuel_colors[fuel],
            pattern = dict(shape = fuel_patterns.get(fuel, ""))
        )
    )

In [203]:
700 * 650 / 800

568.75

In [204]:
years = list(range(2015, 2051, 5))

fig = make_subplots(
    rows=1, cols=2,
    shared_yaxes=True,
    shared_xaxes=True,
    subplot_titles=("Current Policies", "Enhanced Ambition")
)

# Add traces from fig1
for tr in fig1.data:
    tr.showlegend = False  # Show legend

    # Apply color and pattern if available
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=1)

for tr in fig2.data:
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=2, secondary_y=False)

# Layout settings
fig.update_layout(
    barmode='stack',
    plot_bgcolor='rgba(0,0,0,0)',
    width=680,
    height=700,
    # title=dict(
    #     text="<b>Panel B</b>",
    #     font=dict(size=28),
    #     x=0.5
    # ),
    yaxis=dict(
        title="mil. toe",
        range=[0, 33],
        showgrid=True,
        gridcolor='lightgray',
        title_font=dict(size=24),
        tickfont=dict(size=21)
    ),
    xaxis=dict(
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        tickfont=dict(size=21)
    ),
    yaxis2=dict(
        range=[0, 33],
        showgrid=True,
        gridcolor='lightgray',
        tickfont=dict(size=21)
    ),
    xaxis2=dict(
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        tickfont=dict(size=21)
    ),
    legend=dict(
        traceorder="reversed",
        font=dict(size=18),
        x=1.02, y=1,
        borderwidth=0
    )
)

# Apply font size to annotations (if any)
fig.update_annotations(font=dict(size=21))

pio.write_image(fig, "./fig/ironsteel_energy_type.png", width=650, height=680, scale=2)

# Show figure
fig.show()

In [205]:
i = 100
q = queries[i]
title = q.title
print(title)
df = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
df['scenario'] = df['scenario'].str.split(',').str[0]
df

industry final energy by tech and fuel

,Units,scenario,region,sector,subsector,technology,input,Year,value
0,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2025,0.000057
1,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2030,0.000278
2,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2035,0.000585
3,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2025,0.000054
4,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2030,0.000204
...,...,...,...,...,...,...,...,...,...
1245,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2015,0.002158
1246,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2020,0.002360
1247,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2025,0.002459
1248,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2030,0.003219
1249,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2035,0.005094

In [206]:
df['Units'].unique()

array(['EJ'], dtype=object)

In [207]:
df['input'].unique()

array(['elect_td_ind', 'H2 wholesale dispensing',
       'refined liquids industrial', 'delivered biomass', 'wholesale gas',
       'H2 wholesale delivery', 'H2 industrial', 'delivered coal',
       'global solar resource', 'regional woodpulp for energy'],
      dtype=object)

In [208]:
# df['fuel'] = df.apply(cat_fuel, axis=1)
df['ind'] = df['sector'].apply(cat_sec)
df.head()

,Units,scenario,region,sector,subsector,technology,input,Year,value,ind
0,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2025,0.000057,Agriculture
1,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2030,0.000278,Agriculture
2,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2035,0.000585,Agriculture
3,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2025,0.000054,Agriculture
4,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2030,0.000204,Agriculture

In [209]:
df[(df['Year'] >= 2015) & (df['sector'] == 'chemical feedstocks')]

,Units,scenario,region,sector,subsector,technology,input,Year,value,ind
137,EJ,Current-Policy,South Korea,chemical feedstocks,coal,coal,delivered coal,2015,0.023107,Chemical
138,EJ,Current-Policy,South Korea,chemical feedstocks,coal,coal,delivered coal,2020,0.015934,Chemical
139,EJ,Current-Policy,South Korea,chemical feedstocks,coal,coal,delivered coal,2025,0.015177,Chemical
140,EJ,Current-Policy,South Korea,chemical feedstocks,coal,coal,delivered coal,2030,0.015975,Chemical
141,EJ,Current-Policy,South Korea,chemical feedstocks,coal,coal,delivered coal,2035,0.014180,Chemical
146,EJ,Current-Policy,South Korea,chemical feedstocks,refined liquids,refined liquids,refined liquids industrial,2015,1.879390,Chemical
147,EJ,Current-Policy,South Korea,chemical feedstocks,refined liquids,refined liquids,refined liquids industrial,2020,1.934960,Chemical
148,EJ,Current-Policy,South Korea,chemical feedstocks,refined liquids,refined liquids,refined liquids industrial,2025,1.899880,Chemical
149,EJ,Current-Policy,South Korea,chemical feedstocks,refined liquids,refined liquids,refined liquids industrial,2030,1.870150,Chemical
150,EJ,Current-Policy,South Korea,chemical feedstocks,refined liquids,refined liquids,refined liquids industrial,2035,1.814210,Chemical
764,EJ,Enhanced-Ambition,South Korea,chemical feedstocks,biomass,biomass,delivered biomass,2030,0.102701,Chemical
765,EJ,Enhanced-Ambition,South Korea,chemical feedstocks,biomass,biomass,delivered biomass,2035,0.158341,Chemical
767,EJ,Enhanced-Ambition,South Korea,chemical feedstocks,coal,coal,delivered coal,2015,0.023107,Chemical
768,EJ,Enhanced-Ambition,South Korea,chemical feedstocks,coal,coal,delivered coal,2020,0.015934,Chemical
769,EJ,Enhanced-Ambition,South Korea,chemical feedstocks,coal,coal,delivered coal,2025,0.015175,Chemical
770,EJ,Enhanced-Ambition,South Korea,chemical feedstocks,coal,coal,delivered coal,2030,0.009336,Chemical
771,EJ,Enhanced-Ambition,South Korea,chemical feedstocks,coal,coal,delivered coal,2035,0.007219,Chemical
776,EJ,Enhanced-Ambition,South Korea,chemical feedstocks,refined liquids,refined liquids,refined liquids industrial,2015,1.879390,Chemical
777,EJ,Enhanced-Ambition,South Korea,chemical feedstocks,refined liquids,refined liquids,refined liquids industrial,2020,1.934960,Chemical
778,EJ,Enhanced-Ambition,South Korea,chemical feedstocks,refined liquids,refined liquids,refined liquids industrial,2025,1.899820,Chemical
779,EJ,Enhanced-Ambition,South Korea,chemical feedstocks,refined liquids,refined liquids,refined liquids industrial,2030,1.711730,Chemical
780,EJ,Enhanced-Ambition,South Korea,chemical feedstocks,refined liquids,refined liquids,refined liquids industrial,2035,1.527780,Chemical

In [210]:
def cat_energy(row):
    sec = row['sector']
    energy = row['input']
    tech = row['technology']

    if sec == 'chemical feedstocks':
        if energy == 'delivered coal':
            return 'coal (feedstock)'
        elif energy == 'refined liquids industrial':
            return 'refined liquids (feedstock)'
        else:
            print('energy')
            return 'others'
    elif tech in ['gas CCS', 'biomass CCS', 'coal CCS', 'refined liquids CCS']:
        return tech
    elif tech in ['hightemp DAC NG', 'hightemp DAC elec', 'lowtemp DAC heatpump']:
        return 'DAC'
    elif tech == 'electricity with solar':
        return 'electricity'
    elif tech == 'gas with solar':
        return 'gas' 
    elif energy in ['H2 wholesale dispensing', 'H2 wholesale delivery', 'H2 industrial']:
        return 'hydrogen'
    elif energy == 'elect_td_ind':
        return 'electricity'
    elif energy in ['refined liquids industrial']:
        return 'refined liquids'
    elif energy in ['delivered biomass', 'regional woodpulp for energy']:
        return 'biomass'
    elif energy in ['wholesale gas']:
        return 'gas'
    elif energy in ['delivered coal']:
        return 'coal'
    else:
        print(energy, tech)
        return 'others'

In [211]:
df['energy'] = df.apply(cat_energy, axis=1)

energy
energy

In [212]:
dfFig = df[(df['Year'] >= 2015) & (df['ind'] == 'Chemical')].groupby(['scenario', 'Year', 'energy'])['value'].sum().reset_index()
dfFig.head()

         scenario  Year            energy     value
0  Current-Policy  2015           biomass  0.011344
1  Current-Policy  2015              coal  0.004646
2  Current-Policy  2015  coal (feedstock)  0.023107
3  Current-Policy  2015       electricity  0.176272
4  Current-Policy  2015               gas  0.060865

In [213]:
dfFig['value'] *= 23.8846

In [214]:
# dfFig['fuel'] = dfFig['fuel'].apply(lambda fuel: fuel.capitalize())
dfFig['energy'].unique()

array(['biomass', 'coal', 'coal (feedstock)', 'electricity', 'gas',
       'refined liquids', 'refined liquids (feedstock)', 'biomass CCS',
       'coal CCS', 'gas CCS', 'refined liquids CCS', 'hydrogen', 'others'],
      dtype=object)

In [215]:
stack_order = [
    'DAC', 'hydrogen', 'electricity', 'biomass CCS', 'biomass', 'gas CCS', 'gas', 'coal CCS', 'coal', 'coal (feedstock)', 'refined liquids CCS', 'refined liquids', 'refined liquids (feedstock)'
]

In [216]:
dfFig['energy'] = pd.Categorical(dfFig['energy'], categories=stack_order, ordered=True)
dfFig = dfFig.sort_values(by=['Year', 'energy'])
dfFig['energy'].unique()

['electricity', 'biomass', 'gas', 'coal', 'coal (feedstock)', ..., 'gas CCS', 'coal CCS', 'refined liquids CCS', 'hydrogen', NaN]
Length: 13
Categories (13, object): ['DAC' < 'hydrogen' < 'electricity' < 'biomass CCS' ... 'coal (feedstock)' < 'refined liquids CCS' < 'refined liquids' < 'refined liquids (feedstock)']

In [217]:
dfAgg1 = dfFig[(dfFig['scenario'] == scenarios[0])]
fig1 = px.bar(dfAgg1, x="Year", y="value", color="energy", title="Current Policy")
dfAgg2 = dfFig[(dfFig['scenario'] == scenarios[1])]
fig2 = px.bar(dfAgg2, x="Year", y="value", color="energy", title="Enhanced Ambition")

In [218]:
# ---- Colour & hatch (“pattern”) settings ------------------------
fuel_colors = {
    "refined liquids CCS": "#FFB785",    # peach
    "refined liquids" : "#EF0C0C",   # vivid red
    "refined liquids (feedstock)" : "pink",   # vivid red
    "coal"           : "#000000",   # solid black
    "coal CCS"       : "#000000",   # same black, but we’ll add a hatch
    "coal (feedstock)" : "grey",
    "biomass CCS" : "rgb(153, 201, 69)",
    "gas"            : "#0186E0",   # bright blue
    "gas CCS"        : "#33A8E2",   # lighter cyan-blue
    "biomass"        : "#099B43",   # medium green
    "electricity"    : "#0057B5",   # deep blue
    "hydrogen"       : "#FED30B",   # golden yellow
    "DAC"            : "#FFFFFF",   # white base; will rely on hatch only
    
}

# optional: hatch / pattern overlay for the categories that are
# drawn with diagonal stripes in the figure
fuel_patterns = {
    "coal CCS": "/",   # forward-slash hatch
    "gas CCS" : "/",   # same
    "refined liquids CCS": "/",
    "biomass CCS": "/",
    # "refined liquids (feedstock)"     : "\\",
    # "coal (feedstock)"     : "\\",  # back-slash hatch
}

# Example of applying in Plotly
import plotly.graph_objects as go

def bar_for(fuel, x, y):
    return go.Bar(
        name   = fuel,
        x      = x,
        y      = y,
        marker = dict(
            color   = fuel_colors[fuel],
            pattern = dict(shape = fuel_patterns.get(fuel, ""))
        )
    )

In [219]:
years = list(range(2015, 2051, 5))

# Create subplots with secondary y-axes
fig = make_subplots(
    rows=1, cols=2,
    shared_yaxes=True,
    shared_xaxes=True,
    subplot_titles=("Current Policy", "Enhanced Ambition")
)

# Add traces from fig1
for tr in fig1.data:
    tr.showlegend = False  # Show legend

    # Apply color and pattern if available
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=1)

for tr in fig2.data:
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=2, secondary_y=False)


# Layout settings
fig.update_layout(
    barmode='stack',
    plot_bgcolor='rgba(0,0,0,0)',
    width=800,
    height=700,
    title=dict(
        # text="<b>Final Energy Consumption in Chemical</b>",
        font=dict(size=24),
        x=0.5
    ),
    yaxis=dict(
        title="mil. toe",
        range=[0, 65],
        showgrid=True,
        gridcolor='lightgray',
        title_font=dict(size=24),
        tickfont=dict(size=21)
    ),
    xaxis=dict(
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        tickfont=dict(size=21)
    ),
    yaxis2=dict(
        range=[0, 65],
        showgrid=True,
        gridcolor='lightgray',
        tickfont=dict(size=21)
    ),
    xaxis2=dict(
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        tickfont=dict(size=21)
    ),
    legend=dict(
        traceorder="reversed",
        font=dict(size=18),
        x=1.02, y=1,
        borderwidth=0
    )
)

# Apply font size to annotations (if any)
fig.update_annotations(font=dict(size=21))

# Show figure
fig.show()

In [220]:
i = 100
q = queries[i]
title = q.title
print(title)
df = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
df['scenario'] = df['scenario'].str.split(',').str[0]
df

industry final energy by tech and fuel

,Units,scenario,region,sector,subsector,technology,input,Year,value
0,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2025,0.000057
1,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2030,0.000278
2,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2035,0.000585
3,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2025,0.000054
4,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2030,0.000204
...,...,...,...,...,...,...,...,...,...
1245,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2015,0.002158
1246,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2020,0.002360
1247,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2025,0.002459
1248,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2030,0.003219
1249,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2035,0.005094

In [221]:
df['Units'].unique()

array(['EJ'], dtype=object)

In [222]:
df['input'].unique()

array(['elect_td_ind', 'H2 wholesale dispensing',
       'refined liquids industrial', 'delivered biomass', 'wholesale gas',
       'H2 wholesale delivery', 'H2 industrial', 'delivered coal',
       'global solar resource', 'regional woodpulp for energy'],
      dtype=object)

In [223]:
# df['fuel'] = df.apply(cat_fuel, axis=1)
df['ind'] = df['sector'].apply(cat_sec)
df.head()

,Units,scenario,region,sector,subsector,technology,input,Year,value,ind
0,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2025,0.000057,Agriculture
1,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2030,0.000278,Agriculture
2,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2035,0.000585,Agriculture
3,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2025,0.000054,Agriculture
4,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2030,0.000204,Agriculture

In [224]:
df[(df['Year'] >= 2015) & (df['ind'] == 'Cement')]

,Units,scenario,region,sector,subsector,technology,input,Year,value,ind
70,EJ,Current-Policy,South Korea,cement,cement,cement,elect_td_ind,2015,1.965640e-02,Cement
71,EJ,Current-Policy,South Korea,cement,cement,cement,elect_td_ind,2020,1.733140e-02,Cement
72,EJ,Current-Policy,South Korea,cement,cement,cement,elect_td_ind,2025,1.650936e-02,Cement
73,EJ,Current-Policy,South Korea,cement,cement,cement,elect_td_ind,2030,1.623073e-02,Cement
74,EJ,Current-Policy,South Korea,cement,cement,cement,elect_td_ind,2035,1.551172e-02,Cement
75,EJ,Current-Policy,South Korea,cement,cement,cement CCS,elect_td_ind,2025,1.602780e-06,Cement
76,EJ,Current-Policy,South Korea,cement,cement,cement CCS,elect_td_ind,2030,6.863230e-06,Cement
77,EJ,Current-Policy,South Korea,cement,cement,cement CCS,elect_td_ind,2035,1.836787e-05,Cement
78,EJ,Current-Policy,South Korea,cement,cement,cement LC3,elect_td_ind,2025,1.614220e-03,Cement
79,EJ,Current-Policy,South Korea,cement,cement,cement LC3,elect_td_ind,2030,4.371700e-03,Cement
80,EJ,Current-Policy,South Korea,cement,cement,cement LC3,elect_td_ind,2035,5.855870e-03,Cement
474,EJ,Current-Policy,South Korea,process heat cement,biomass,biomass,delivered biomass,2015,3.986150e-02,Cement
475,EJ,Current-Policy,South Korea,process heat cement,biomass,biomass,delivered biomass,2020,3.706120e-02,Cement
476,EJ,Current-Policy,South Korea,process heat cement,biomass,biomass,delivered biomass,2025,3.793302e-02,Cement
477,EJ,Current-Policy,South Korea,process heat cement,biomass,biomass,delivered biomass,2030,3.961035e-02,Cement
478,EJ,Current-Policy,South Korea,process heat cement,biomass,biomass,delivered biomass,2035,3.629529e-02,Cement
482,EJ,Current-Policy,South Korea,process heat cement,coal,coal,delivered coal,2015,1.146530e-01,Cement
483,EJ,Current-Policy,South Korea,process heat cement,coal,coal,delivered coal,2020,1.067240e-01,Cement
484,EJ,Current-Policy,South Korea,process heat cement,coal,coal,delivered coal,2025,1.093613e-01,Cement
485,EJ,Current-Policy,South Korea,process heat cement,coal,coal,delivered coal,2030,1.156042e-01,Cement
486,EJ,Current-Policy,South Korea,process heat cement,coal,coal,delivered coal,2035,1.142031e-01,Cement
487,EJ,Current-Policy,South Korea,process heat cement,hydrogen,hydrogen,H2 industrial,2025,2.227110e-07,Cement
488,EJ,Current-Policy,South Korea,process heat cement,hydrogen,hydrogen,H2 industrial,2030,4.569826e-05,Cement
489,EJ,Current-Policy,South Korea,process heat cement,hydrogen,hydrogen,H2 industrial,2035,6.925297e-05,Cement
494,EJ,Current-Policy,South Korea,process heat cement,refined liquids,refined liquids,refined liquids industrial,2015,2.107020e-02,Cement
495,EJ,Current-Policy,South Korea,process heat cement,refined liquids,refined liquids,refined liquids industrial,2020,1.103120e-02,Cement
496,EJ,Current-Policy,South Korea,process heat cement,refined liquids,refined liquids,refined liquids industrial,2025,8.541980e-03,Cement
497,EJ,Current-Policy,South Korea,process heat cement,refined liquids,refined liquids,refined liquids industrial,2030,9.608556e-03,Cement
498,EJ,Current-Policy,South Korea,process heat cement,refined liquids,refined liquids,refined liquids industrial,2035,1.314623e-02,Cement
698,EJ,Enhanced-Ambition,South Korea,cement,cement,cement,elect_td_ind,2015,1.965640e-02,Cement
699,EJ,Enhanced-Ambition,South Korea,cement,cement,cement,elect_td_ind,2020,1.733200e-02,Cement
700,EJ,Enhanced-Ambition,South Korea,cement,cement,cement,elect_td_ind,2025,1.650045e-02,Cement
701,EJ,Enhanced-Ambition,South Korea,cement,cement,cement,elect_td_ind,2030,1.317195e-02,Cement
702,EJ,Enhanced-Ambition,South Korea,cement,cement,cement,elect_td_ind,2035,1.118580e-02,Cement
703,EJ,Enhanced-Ambition,South Korea,cement,cement,cement CCS,elect_td_ind,2025,1.608200e-06,Cement
704,EJ,Enhanced-Ambition,South Korea,cement,cement,cement CCS,elect_td_ind,2030,3.080430e-05,Cement
705,EJ,Enhanced-Ambition,South Korea,cement,cement,cement CCS,elect_td_ind,2035,1.156064e-04,Cement
706,EJ,Enhanced-Ambition,South Korea,cement,cement,cement LC3,elect_td_ind,2025,1.611120e-03,Cement
707,EJ,Enhanced-Ambition,South Korea,cement,cement,cement LC3,elect_td_ind,2030,5.100020e-03,Cement
708,EJ,Enhanced-Ambition,South Korea,cement,cement,cement LC3,elect_td_ind,2035,7.605540e-03,Cement
1104,EJ,Enhanced-Ambition,South Korea,process heat cement,biomass,biomass,delivered biomass,2015,3.986150e-02,Cement
1105,EJ,Enhanced-Ambition,South Korea,process heat cement,biomass,biomass,delivered biomass,2020,3.706330e-02,Cement
1106,EJ,Enhanced-Ambition,South Korea,process heat cement,biomass,biomass,delivered biomass,2025,3.790668e-02,Cement
1107,EJ,Enhanced-Ambition,South Korea,process heat cement,biomass,biomass,delivered biomass,2030,3.583659e-02,Cement
1108,EJ,Enhanced-Ambition,South Korea,process heat cement,biomass,biomass,delivered biomass,2035,3.623160e-02,Cement
1112,EJ,Enhanced-Ambition,South Korea,process heat cement,coal,coal,delivered coal,2015,1.146530e-01,Cement
1113,EJ,Enhanced-Ambition,South Korea,process heat cement,coal,coal,delivered coal,2020,1.067290e-01,Cement
1114,EJ,Enhanced-Ambition,South Korea,process heat cement,coal,coal,delivered coal,2025,1.092993e-01,Cement
1115,EJ,Enhanced-Ambition,South Korea,process heat cement,coal,coal,delivered coal,2030,9.876545e-02,Cement
1116,EJ,Enhanced-Ambition,South Korea,process heat cement,coal,coal,delivered coal,2035,8.895598e-02,Cement
1117,EJ,Enhanced-Ambition,South Korea,process heat cement,hydrogen,hydrogen,H2 industrial,2025,1.604620e-07,Cement
1118,EJ,Enhanced-Ambition,South Korea,process heat cement,hydrogen,hydrogen,H2 industrial,2030,9.305750e-05,Cement
1119,EJ,Enhanced-Ambition,South Korea,process heat cement,hydrogen,hydrogen,H2 industrial,2035,5.348445e-04,Cement
1124,EJ,Enhanced-Ambition,South Korea,process heat cement,refined liquids,refined liquids,refined liquids industrial,2015,2.107020e-02,Cement
1125,EJ,Enhanced-Ambition,South Korea,process heat cement,refined liquids,refined liquids,refined liquids industrial,2020,1.102830e-02,Cement
1126,EJ,Enhanced-Ambition,South Korea,process heat cement,refined liquids,refined liquids,refined liquids industrial,2025,8.538222e-03,Cement
1127,EJ,Enhanced-Ambition,South Korea,process heat cement,refined liquids,refined liquids,refined liquids industrial,2030,1.273374e-02,Cement
1128,EJ,Enhanced-Ambition,South Korea,process heat cement,refined liquids,refined liquids,refined liquids industrial,2035,1.930028e-02,Cement

In [225]:
def cat_energy(row):
    energy = row['input']
    tech = row['technology']
    
    if tech in ['gas CCS', 'biomass CCS', 'coal CCS', 'refined liquids CCS']:
        return tech
    elif tech == 'electricity with solar':
        return 'electricity'
    elif tech == 'gas with solar':
        return 'gas'
    elif energy in ['H2 wholesale dispensing', 'H2 wholesale delivery', 'H2 industrial']:
        return 'hydrogen'
    elif energy == 'elect_td_ind':
        return 'electricity'
    elif energy in ['refined liquids industrial']:
        return 'refined liquids'
    elif energy in ['delivered biomass', 'regional woodpulp for energy']:
        return 'biomass'
    elif energy in ['wholesale gas']:
        return 'gas'
    elif energy in ['delivered coal']:
        return 'coal'
    else:
        print(energy, tech)
        return 'others'

In [226]:
df['energy'] = df.apply(cat_energy, axis=1)

In [227]:
dfFig = df[(df['Year'] >= 2015) & (df['ind'] == 'Cement')].groupby(['scenario', 'Year', 'energy'])['value'].sum().reset_index()
dfFig.head()

         scenario  Year           energy     value
0  Current-Policy  2015          biomass  0.039862
1  Current-Policy  2015             coal  0.114653
2  Current-Policy  2015      electricity  0.019656
3  Current-Policy  2015  refined liquids  0.021070
4  Current-Policy  2020          biomass  0.037061

In [228]:
dfFig['value'] *= 23.8846

In [229]:
# dfFig['fuel'] = dfFig['fuel'].apply(lambda fuel: fuel.capitalize())
dfFig['energy'].unique()

array(['biomass', 'coal', 'electricity', 'refined liquids', 'hydrogen'],
      dtype=object)

In [230]:
stack_order = [
    'hydrogen', 'electricity', 'biomass CCS', 'biomass', 'gas CCS', 'gas', 'coal CCS', 'coal', 'refined liquids CCS', 'refined liquids', 'hydrogen (for heat)', 'biomass (for heat)', 'coal (for heat)', 'refined liquids (for heat)', 
]

In [231]:
dfFig['energy'] = pd.Categorical(dfFig['energy'], categories=stack_order, ordered=True)
dfFig = dfFig.sort_values(by=['Year', 'energy'])
dfFig['energy'].unique()

['electricity', 'biomass', 'coal', 'refined liquids', 'hydrogen']
Categories (14, object): ['hydrogen' < 'electricity' < 'biomass CCS' < 'biomass' ... 'hydrogen (for heat)' < 'biomass (for heat)' < 'coal (for heat)' < 'refined liquids (for heat)']

In [232]:
dfAgg1 = dfFig[(dfFig['scenario'] == scenarios[0])]
fig1 = px.bar(dfAgg1, x="Year", y="value", color="energy", title="Current Policy")
dfAgg2 = dfFig[(dfFig['scenario'] == scenarios[1])]
fig2 = px.bar(dfAgg2, x="Year", y="value", color="energy", title="Enhanced Ambition")

In [233]:
# ---- Colour & hatch (“pattern”) settings ------------------------
fuel_colors = {
    "refined liquids CCS": "#FFB785",    # peach
    "refined liquids" : "#EF0C0C",   # vivid red
    "coal"           : "#000000",   # solid black
    "coal CCS"       : "#000000",   # same black, but we’ll add a hatch
    "gas"            : "#0186E0",   # bright blue
    "gas CCS"        : "#33A8E2",   # lighter cyan-blue
    "biomass"        : "#099B43",   # medium green
    "electricity"    : "#0057B5",   # deep blue
    "hydrogen"       : "#FED30B",   # golden yellow
}

# optional: hatch / pattern overlay for the categories that are
# drawn with diagonal stripes in the figure
fuel_patterns = {
    "coal CCS": "/",   # forward-slash hatch
    "gas CCS" : "/",   # same
    "refined liquids CCS": "/",
    "biomass CCS": "/",
    "DAC"     : "\\",  # back-slash hatch
}

# Example of applying in Plotly
import plotly.graph_objects as go

def bar_for(fuel, x, y):
    return go.Bar(
        name   = fuel,
        x      = x,
        y      = y,
        marker = dict(
            color   = fuel_colors[fuel],
            pattern = dict(shape = fuel_patterns.get(fuel, ""))
        )
    )

In [234]:
years = list(range(2015, 2051, 5))

# Create subplots with secondary y-axes
fig = make_subplots(
    rows=1, cols=2,
    shared_yaxes=True,
    shared_xaxes=True,
    subplot_titles=("Current Policy", "Enhanced Ambition")
)

# Add traces from fig1
for tr in fig1.data:
    tr.showlegend = False  # Show legend

    # Apply color and pattern if available
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=1)

for tr in fig2.data:
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=2, secondary_y=False)

# Layout settings
fig.update_layout(
    barmode='stack',
    plot_bgcolor='rgba(0,0,0,0)',
    width=800,
    height=700,
    title=dict(
        # text="<b>Final Energy Consumption in Cement</b>",
        font=dict(size=24),
        x=0.5
    ),
    yaxis=dict(
        title="mil. toe",
        range=[0, 6.5],
        showgrid=True,
        gridcolor='lightgray',
        title_font=dict(size=24),
        tickfont=dict(size=21)
    ),
    xaxis=dict(
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        tickfont=dict(size=21)
    ),
    yaxis2=dict(
        range=[0, 6.5],
        showgrid=True,
        gridcolor='lightgray',
        tickfont=dict(size=21)
    ),
    xaxis2=dict(
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        tickfont=dict(size=21)
    ),
    legend=dict(
        traceorder="reversed",
        font=dict(size=18),
        x=1.02, y=1,
        borderwidth=0
    )
)

# Apply font size to annotations (if any)
fig.update_annotations(font=dict(size=21))

# Show figure
fig.show()

In [227]:
i = 100
q = queries[i]
title = q.title
print(title)
df = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
df['scenario'] = df['scenario'].str.split(',').str[0]
df

industry final energy by tech and fuel

,Units,scenario,region,sector,subsector,technology,input,Year,value
0,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2025,0.000057
1,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2030,0.000278
2,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2035,0.000585
3,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2025,0.000054
4,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2030,0.000204
...,...,...,...,...,...,...,...,...,...
1245,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2015,0.002158
1246,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2020,0.002360
1247,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2025,0.002459
1248,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2030,0.003219
1249,EJ,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,regional woodpulp for energy,2035,0.005094

In [228]:
df['Units'].unique()

array(['EJ'], dtype=object)

In [229]:
df['input'].unique()

array(['elect_td_ind', 'H2 wholesale dispensing',
       'refined liquids industrial', 'delivered biomass', 'wholesale gas',
       'H2 wholesale delivery', 'H2 industrial', 'delivered coal',
       'global solar resource', 'regional woodpulp for energy'],
      dtype=object)

In [230]:
# df['fuel'] = df.apply(cat_fuel, axis=1)
df['ind'] = df['sector'].apply(cat_sec)
df.head()

,Units,scenario,region,sector,subsector,technology,input,Year,value,ind
0,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2025,0.000057,Agriculture
1,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2030,0.000278,Agriculture
2,EJ,Current-Policy,South Korea,agricultural energy use,mobile,electricity,elect_td_ind,2035,0.000585,Agriculture
3,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2025,0.000054,Agriculture
4,EJ,Current-Policy,South Korea,agricultural energy use,mobile,hydrogen,H2 wholesale dispensing,2030,0.000204,Agriculture

In [231]:
df[(df['Year'] >= 2015) & (~df['ind'].isin(['Iron and Steel', 'Chemical', 'Cement']))]['sector'].unique()

array(['agricultural energy use', 'construction energy use',
       'construction feedstocks', 'food processing', 'mining energy use',
       'other industrial energy use', 'other industrial feedstocks',
       'paper', 'process heat food processing', 'process heat paper',
       'waste biomass for paper', 'CO2 removal', 'process heat dac'],
      dtype=object)

In [232]:
def cat_energy(row):
    sec = row['sector']
    energy = row['input']
    tech = row['technology']

    if 'feedstocks' in sec:
        suffix = " (feedstock)"
    else:
        suffix = ''
    
    if tech in ['gas CCS', 'biomass CCS', 'coal CCS', 'refined liquids CCS']:
        return tech + suffix
    elif tech == 'electricity with solar':
        return 'electricity' + suffix
    elif tech == 'gas with solar':
        return 'gas' + suffix
    elif energy in ['H2 wholesale dispensing', 'H2 wholesale delivery', 'H2 industrial']:
        return 'hydrogen' + suffix
    elif energy == 'elect_td_ind':
        return 'electricity' + suffix
    elif energy in ['refined liquids industrial']:
        return 'refined liquids' + suffix
    elif energy in ['delivered biomass', 'regional woodpulp for energy']:
        return 'biomass' + suffix
    elif energy in ['wholesale gas']:
        return 'gas' + suffix
    elif energy in ['delivered coal']:
        return 'coal' + suffix
    else:
        print(energy, tech)
        return 'others' + suffix

In [233]:
df['energy'] = df.apply(cat_energy, axis=1)
df[(df['energy'].isna())]

Empty DataFrame
Columns: [Units, scenario, region, sector, subsector, technology, input, Year, value, ind, energy]
Index: []

In [234]:
df['energy'].unique()

array(['electricity', 'hydrogen', 'refined liquids', 'biomass', 'gas',
       'gas CCS', 'biomass CCS', 'coal', 'coal CCS',
       'refined liquids CCS', 'coal (feedstock)',
       'refined liquids (feedstock)', 'biomass (feedstock)'], dtype=object)

In [255]:
dfFig = df[(df['Year'] >= 2015) & (~df['ind'].isin(['Iron and Steel', 'Chemical', 'Cement']))].groupby(['scenario', 'Year', 'energy'])['value'].sum().reset_index()
dfFig.head()

         scenario  Year           energy     value
0  Current-Policy  2015          biomass  0.113423
1  Current-Policy  2015             coal  0.318681
2  Current-Policy  2015      electricity  0.586204
3  Current-Policy  2015              gas  0.226236
4  Current-Policy  2015  refined liquids  0.230988

In [246]:
dfFig['value'] *= 23.8846

In [247]:
# dfFig['fuel'] = dfFig['fuel'].apply(lambda fuel: fuel.capitalize())
dfFig['energy'].unique()

array(['biomass', 'coal', 'electricity', 'gas', 'refined liquids',
       'refined liquids (feedstock)', 'hydrogen'], dtype=object)

In [248]:
stack_order = [
    'hydrogen', 'electricity', 'biomass CCS', 'biomass', 'gas CCS', 'gas', 'coal CCS', 'coal', 'refined liquids CCS', 'refined liquids', 'refined liquids (feedstock)',
]

In [249]:
dfFig['energy'] = pd.Categorical(dfFig['energy'], categories=stack_order, ordered=True)
dfFig = dfFig.sort_values(by=['Year', 'energy'])
dfFig['energy'].unique()

['electricity', 'biomass', 'gas', 'coal', 'refined liquids', 'refined liquids (feedstock)', 'hydrogen']
Categories (11, object): ['hydrogen' < 'electricity' < 'biomass CCS' < 'biomass' ... 'coal' < 'refined liquids CCS' < 'refined liquids' < 'refined liquids (feedstock)']

In [250]:
dfAgg1 = dfFig[(dfFig['scenario'] == scenarios[0])]
fig1 = px.bar(dfAgg1, x="Year", y="value", color="energy", title="Current Policy")
dfAgg2 = dfFig[(dfFig['scenario'] == scenarios[1])]
fig2 = px.bar(dfAgg2, x="Year", y="value", color="energy", title="Enhanced Ambition")

In [251]:
# ---- Colour & hatch (“pattern”) settings ------------------------
fuel_colors = {
    "refined liquids CCS": "#FFB785",    # peach
    "refined liquids (feedstock)" : "#FFB785",   # vivid red
    "refined liquids" : "#EF0C0C",   # vivid red
    "coal"           : "#000000",   # solid black
    "coal CCS"       : "grey",   # same black, but we’ll add a hatch
    "biomass CCS" : "rgb(153, 201, 69)",
    "gas"            : "#0186E0",
    "gas CCS"        : "#33A8E2",   # lighter cyan-blue
    "biomass"        : "#099B43",
    "electricity"    : "#0057B5",
    "hydrogen"       : "#FED30B",   # golden yellow
}

# optional: hatch / pattern overlay for the categories that are
# drawn with diagonal stripes in the figure
fuel_patterns = {
    "coal CCS": "/",   # forward-slash hatch
    "gas CCS" : "/",   # same
    "refined liquids CCS": "/",
    "biomass CCS": "/",
    "refined liquids (feedstock)"     : "/",
}

# Example of applying in Plotly
import plotly.graph_objects as go

def bar_for(fuel, x, y):
    return go.Bar(
        name   = fuel,
        x      = x,
        y      = y,
        marker = dict(
            color   = fuel_colors[fuel],
            pattern = dict(shape = fuel_patterns.get(fuel, ""))
        )
    )

In [254]:
years = list(range(2015, 2051, 5))

fig = make_subplots(
    rows=1, cols=2,
    shared_yaxes=True,
    shared_xaxes=True,
    subplot_titles=("Current Policy", "Enhanced Ambition")
)

# Add traces from fig1
for tr in fig1.data:
    tr.showlegend = False  # Show legend

    # Apply color and pattern if available
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=1)

for tr in fig2.data:
    if tr.name in fuel_colors:
        tr.marker.color = fuel_colors[tr.name]
        pattern = fuel_patterns.get(tr.name)
        if pattern:
            tr.marker.pattern = dict(shape=pattern)

    fig.add_trace(tr, row=1, col=2, secondary_y=False)

# Layout settings
fig.update_layout(
    barmode='stack',
    plot_bgcolor='rgba(0,0,0,0)',
    width=800,
    height=700,
    title=dict(
        # text="<b>Final Energy Consumption in Other Industry</b>",
        font=dict(size=24),
        x=0.5
    ),
    yaxis=dict(
        title="mil. toe",
        range=[0, 43],
        showgrid=True,
        gridcolor='lightgray',
        title_font=dict(size=24),
        tickfont=dict(size=21)
    ),
    xaxis=dict(
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        tickfont=dict(size=21)
    ),
    yaxis2=dict(
        range=[0, 43],
        showgrid=True,
        gridcolor='lightgray',
        tickfont=dict(size=21)
    ),
    xaxis2=dict(
        tickvals=years,
        ticktext=[str(y) for y in years],
        tickangle=45,
        tickfont=dict(size=21)
    ),
    legend=dict(
        traceorder="reversed",
        font=dict(size=18),
        x=1.02, y=1,
        borderwidth=0
    )
)

# Apply font size to annotations (if any)
fig.update_annotations(font=dict(size=21))

# Show figure
fig.show()