In [28]:
from pathlib import Path
import gcamreader
import os
import pandas as pd
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [29]:
def to_Mt(row):
    val, unit = row['value'], row['Units']
    if unit == 'Tg':
        return val
    elif unit == 'Gg':
        return val * 1e-3
    elif unit == 'MTC':
        return val * (44.009 / 12.011)
    else:
        raise ValueError(f"Unknown unit: {unit}")

# AR5 100-yr GWP
GWP_AR5 = {
    'CO2':    1,
    'CH4':    28,
    'N2O':    265,
    'HFC125': 3500,
    'HFC134a':1430,
    'HFC143a':4470,
    'HFC23':  14800,
    'HFC32':  675,
    'HFC43':  1500,
    'HFC227ea':3220,
    'HFC236fa':9810,
    'SF6':    23500,
    'C2F6':   12200,
    'CF4':    6630,
}

In [30]:
proj_path = Path("/data/project/tae/gcam-core")
xml_path = proj_path / "input" / "gcamdata" / "xml"
db_path = proj_path / "output"

In [31]:
dbpath = "../output/"  # relative to current working directory
dbfile = "database_basexdb_korea_2035_20250721_7"
conn = gcamreader.LocalDBConn(dbpath, dbfile)
queries = gcamreader.parse_batch_query(os.path.join('..', 'output', 'queries','Main_queries.xml'))

Database scenarios: Current-Policy, Current-Policy, Enhanced-Ambition

In [32]:
scenarios = list(conn.listScenariosInDB()['name'])
scenarios

['Current-Policy', 'Current-Policy', 'Enhanced-Ambition']

In [33]:
scenarios=['Current-Policy', 'Enhanced-Ambition']

In [59]:
scenarios.reverse()

In [60]:
for i, q in enumerate(queries):
    print(i, q.title)

0 primary energy consumption by region (avg fossil efficiency)
1 primary energy consumption by region (direct equivalent)
2 primary energy consumption with CCS by region (direct equivalent)
3 resource production
4 resource production by tech and vintage
5 resource supply curves
6 regional primary energy prices
7 elec gen by region (incl CHP)
8 elec gen by subsector
9 elec gen by gen tech
10 elec gen by gen tech and cooling tech
11 elec gen by gen tech and cooling tech and vintage
12 elec gen by gen tech and cooling tech (new)
13 elec energy input by subsector
14 elec energy input by elec gen tech
15 elec energy input by elec gen tech and cooling tech
16 elec prices by sector
17 elec gen costs by subsector
18 elec gen costs by tech
19 elec gen costs by cooling tech
20 elec share-weights by subsector
21 elec share-weights by tech
22 elec share-weights by cooling tech
23 elec td inputs and outputs
24 cogeneration by region
25 elec consumption by demand sector
26 elec sector water withdrawals
27 elec sector water consumption
28 elec water withdrawals by gen tech
29 elec water consumption by gen tech
30 elec water withdrawals by gen tech and cooling tech
31 elec water consumption by gen tech and cooling tech
32 elec water withdrawals by gen tech and cooling tech (new)
33 elec water consumption by gen tech and cooling tech (new)
34 refined liquids production by region
35 refined liquids production by subsector
36 refined liquids production by tech
37 refined liquids production by tech and vintage
38 refined liquids production by tech (new)
39 refinery inputs by tech (energy and feedstocks)
40 refined liquids prices by sector
41 refined liquids costs by subsector
42 refined liquids costs by tech
43 refining and oil share-weights by subsector
44 refining share-weights by tech
45 hydrogen production by tech
46 hydrogen inputs by tech
47 hydrogen prices by sector
48 hydrogen costs by tech
49 hydrogen technology IO coefficients
50 hydrogen utilization by technology
51 hydrogen non-energy costs
52 hydrogen outputs by technology
53 hydrogen dispensing energy by primary fuel
54 gas production by tech
55 gas production share-weights by subsector
56 gas inputs by tech (energy and feedstocks)
57 gas pipeline inputs and outputs
58 gas prices by sector
59 gas costs by tech
60 gas consumption by sector
61 delivered gas energy by primary fuel
62 district heat production by subsector (fuel)
63 district heat energy inputs by subsector
64 total final energy by region
65 total final energy by aggregate sector
66 total final energy by sector
67 final energy consumption by fuel
68 final energy consumption by sector and fuel
69 final energy prices
70 building floorspace
71 building floorspace per capita
72 building commercial floorspace satiation impedance
73 building residential floorspace regional bias adder
74 building total final energy by region
75 building total final energy by service
76 building final energy by fuel
77 building final energy by service and fuel
78 building final energy by subsector
79 building final energy by tech
80 building final energy by tech and vintage
81 building final energy by tech (new)
82 building service output by service
83 building service output by subsector
84 building service output by tech
85 building service output by tech and vintage
86 building service output by tech (new)
87 building service density by energy service
88 building satiation impedance by energy service
89 building regional bias adder by energy service
90 building internal gain energy by service
91 total service cost per unit floorspace
92 building service costs
93 fuel prices to buildings
94 building share-weights by subsector
95 building share-weights by tech
96 industry total final energy by region
97 industry total final energy by service
98 industry final energy by fuel
99 industry final energy by service and fuel
100 industry final energy by tech and fuel
101 industry feedstocks by type
102 industry primary output by sector
103 industry cogeneration by fuel
104 fuel prices to industry
105 industry share-weights by subsector
106 industry water withdrawals and consumption
107 cement production by region
108 cement production by tech (conv and ccs)
109 cement production by tech and vintage
110 inputs to cement production
111 cement prices
112 ammonia production by region
113 ammonia production by tech
114 ammonia inputs by tech (energy and feedstocks)
115 ammonia and N fertilizer prices
116 ammonia domestic supply
117 ammonia exports (query USA region)
118 iron and steel production by region
119 iron and steel production by tech
120 iron and steel production by tech and vintage
121 iron and steel inputs by tech (energy and feedstocks)
122 iron and steel prices
123 traded iron and steel
124 regional iron and steel sources
125 chemical production by region
126 chemical inputs by tech (energy and feedstocks)
127 chemical prices
128 aluminum production by region
129 aluminum production by tech
130 aluminum production by tech and vintage
131 aluminum inputs by tech (energy and feedstocks)
132 aluminum prices
133 construction inputs (energy and feedstocks)
134 agricultural energy use
135 mining energy use
136 food processing production by region
137 food processing process heat production by tech
138 inputs to food processing
139 inputs to food processing (process heat separated)
140 food processing prices
141 paper production by region
142 inputs to paper production
143 paper prices
144 energy-for-water TFE
145 energy-for-water FE by fuel
146 energy-for-water FE by process and fuel
147 prices of energy-for-water processes
148 water flow volumes of EFW processes
149 nonrenewable groundwater pumping energy
150 transport total final energy by region
151 transport total final energy by service
152 transport final energy by fuel
153 transport final energy by mode and fuel
154 transport final energy by tech and fuel
155 transport final energy by tech and vintage
156 transport final energy by tech (new)
157 transport service output by service
158 transport service output by mode
159 transport service output by tech
160 transport service output by tech and vintage
161 transport service output by tech (new)
162 transport load factors
163 fuel prices to transport
164 costs of transport services
165 costs of transport modes
166 costs of transport techs
167 transport tech non-energy cost
168 LDV energy by primary fuel
169 transport subsector share-weights
170 transport tech share-weights
171 transport speeds
172 building final energy by tech
173 building service output by tech
174 building floorspace
175 industry final energy by service and fuel
176 transport final energy by tech and fuel
177 transport final energy by tech (new)
178 transport service output by tech
179 transport service output by tech (new)
180 detailed land allocation
181 detailed historical land allocation
182 land allocation by crop
183 aggregated land allocation
184 aggregated historical land allocation
185 land allocation in a specified land use region
186 land allocation by crop and water source
187 LUC emissions by region
188 LUC emissions by LUT
189 LUC emissions by LUT in a specified land use region
190 vegetative carbon stock by region
191 profit rate
192 profit rate in a specified land use region
193 land leaf shares
194 land leaf shares in a specified land use region
195 ag production by crop type
196 ag production by subsector (land use region)
197 ag production in a specified land use region
198 ag production by tech
199 ag tech variable cost
200 ag tech yield
201 ag tech yield in a specified land region
202 ag commodity prices
203 ag tech implied subsidy
204 irrigation water withdrawals by region
205 irrigation water withdrawals by crop type
206 irrigation water withdrawals by crop type and land region
207 irrigation water withdrawals by ag tech
208 irrigation water consumption by region
209 irrigation water consumption by crop type
210 irrigation water consumption by crop type and land region
211 irrigation water consumption by ag tech
212 biophysical water demand by region
213 biophysical water demand by crop type
214 biophysical water demand by crop type and land region
215 biophysical water demand by ag tech
216 fertilizer consumption by region
217 fertilizer consumption by crop type
218 fertilizer consumption by ag tech
219 fertilizer-crop input-output coefficients
220 purpose-grown biomass production
221 residue biomass production
222 MSW production
223 regional biomass consumption
224 meat and dairy production by type
225 meat and dairy production by tech
226 meat and dairy prices
227 meat and dairy subsector share-weights
228 meat and dairy tech share-weights
229 meat and dairy subsector costs
230 meat and dairy tech costs
231 water consumption by meat and dairy production
232 feed consumption by region
233 feed consumption by meat and dairy tech
234 feed sources
235 feed prices
236 feed subsector share-weights
237 food consumption by type (general)
238 food consumption by type (specific)
239 demand balances by crop commodity
240 demand balances by meat and dairy commodity
241 food demand prices
242 food demand
243 food demand per capita
244 food demand regional bias
245 ag import vs. domestic supply (Regional Armington competition)
246 ag export to the world center (USA) (Intl. Armington competition)
247 ag import vs. domestic prices
248 ag export prices (at world center USA)
249 import vs. domestic share-weights (Armington regional taste)
250 international competition share-weights (Armington intl. taste)
251 ag total prices (weighted average b/t domestic and imported prices)
252 opening stocks (supply from carryover)
253 closing stocks (before loss/adjustments)
254 closing stocks (after loss/adjustments; carried over)
255 current supply (current or regional consumption)
256 ag regional prices (current consumer prices)
257 agricultural storage share-weights
258 storage cost
259 expected price
260 CO2 emissions by region
261 CO2 emissions by sector (excluding resource production)
262 CO2 emissions by sector (no bio) (excluding resource production)
263 CO2 emissions by assigned sector (no bio) (excluding resource production)
264 CO2 emissions by subsector (excluding resource production)
265 CO2 emissions by tech (excluding resource production)
266 CO2 emissions by resource production
267 CO2 sequestration by sector
268 CO2 sequestration by tech
269 nonCO2 emissions by region
270 nonCO2 emissions by sector (excluding resource production)
271 nonCO2 emissions by resource production
272 nonCO2 emissions by subsector (excluding resource production)
273 nonCO2 emissions by tech (excluding resource production)
274 specific nonCO2 emissions by region
275 specific nonCO2 emissions by sector (excluding resource production)
276 specific nonCO2 emissions by resource production
277 specific nonCO2 emissions by subsector (excluding resource production)
278 specific nonCO2 emissions by tech (excluding resource production)
279 CO2 concentrations
280 total climate forcing
281 global mean temperature
282 net terrestrial C uptake
283 population by region
284 GDP MER by region
285 GDP per capita MER by region
286 GDP per capita PPP by region
287 subregional population
288 subregional income
289 National Account
290 Social Accounting Matrix
291 Tracking accounts by tech
292 Capital investment demands by tech
293 Capital investment demands by resource
294 CO2 prices
295 policy cost by period
296 undiscounted policy cost
297 discounted policy cost
298 regional CO2 MAC curves by period
299 water withdrawals by region
300 water withdrawals by water mapping source
301 water withdrawals by sector
302 water withdrawals by subsector
303 water withdrawals by tech
304 water consumption by region
305 water consumption by water mapping source
306 water consumption by sector
307 water consumption by subsector
308 water consumption by tech
309 Basin level available runoff
310 Water withdrawals by water source (runoff vs. groundwater)
311 Water Withdrawals by Basin (Runoff)
312 Water Withdrawals by Basin (Groundwater)
313 Cumulative groundwater extraction
314 prices of all markets
315 supply of all markets
316 demand of all markets
317 price of a specific market
318 supply of a specific market
319 prices by sector
320 costs by subsector
321 costs by tech
322 costs by tech and input
323 inputs by sector
324 inputs by subsector
325 inputs by tech
326 outputs by sector
327 outputs by subsector
328 outputs by tech
329 input-output coefficients by tech
330 primary energy consumption by region (direct equivalent)
331 industry water withdrawals and consumption
332 elec gen by region (no CHP)
333 elec gen by subsector
334 elec gen by gen tech (cogen only)
335 elec gen by gen tech and cooling tech (incl cogen)
336 elec energy input by subsector
337 elec energy input by elec gen tech
338 elec prices by sector
339 elec gen costs by subsector
340 elec gen costs by tech
341 elec share-weights by subsector
342 elec share-weights by gen tech
343 elec share-weights by cooling tech
344 elec water withdrawals by gen tech and cooling tech
345 elec water consumption by gen tech and cooling tech
346 refined liquids production by region
347 refined liquids production by subsector
348 refined liquids production by tech
349 refined liquids production by tech and vintage
350 refined liquids production by tech (new)
351 refinery inputs by tech (energy and feedstocks)
352 refined liquids prices by sector
353 refined liquids costs by subsector
354 refined liquids costs by tech
355 refining and oil share-weights by subsector
356 refining share-weights by tech
357 total final energy by aggregate sector
358 water withdrawals by state, sector, basin
359 water withdrawals by state, sector, basin (includes desal)
360 water consumption by state, sector, basin
361 water consumption by state, sector, basin (includes desal)
362 CO2 emissions by tech (nested subsector) (excluding resource production)
363 CO2 sequestration by tech (nested subsector)

In [61]:
i = 170
q = queries[i]
title = q.title
print(title)
df = conn.runQuery(q, scenarios=['Enhanced-Ambition'], regions=['South Korea'])
df['scenario'] = df['scenario'].str.split(',').str[0]
df

transport tech share-weights

,Units,scenario,region,sector,subsector,Year,technology,value
0,None Specified,Enhanced-Ambition,South Korea,trn_aviation_intl,International Aviation,1975,Liquids,1.0
1,None Specified,Enhanced-Ambition,South Korea,trn_aviation_intl,International Aviation,1990,Liquids,1.0
2,None Specified,Enhanced-Ambition,South Korea,trn_aviation_intl,International Aviation,2005,Liquids,1.0
3,None Specified,Enhanced-Ambition,South Korea,trn_aviation_intl,International Aviation,2010,Liquids,1.0
4,None Specified,Enhanced-Ambition,South Korea,trn_aviation_intl,International Aviation,2015,Liquids,1.0
...,...,...,...,...,...,...,...,...
906,None Specified,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,2095,Liquids,1.0
907,None Specified,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,2100,BEV,1.0
908,None Specified,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,2100,FCEV,1.0
909,None Specified,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,2100,Hybrid Liquids,1.0
910,None Specified,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,2100,Liquids,1.0

In [62]:
df[(df['Year'] == 2035) & (df['subsector'] == 'Bus')]

,Units,scenario,region,sector,subsector,Year,technology,value
507,None Specified,Enhanced-Ambition,South Korea,trn_pass_road,Bus,2035,BEV,0.571429
508,None Specified,Enhanced-Ambition,South Korea,trn_pass_road,Bus,2035,FCEV,0.235294
509,None Specified,Enhanced-Ambition,South Korea,trn_pass_road,Bus,2035,Liquids,0.333333
510,None Specified,Enhanced-Ambition,South Korea,trn_pass_road,Bus,2035,NG,0.206280

In [63]:
df[(df['Year'] == 2035) & (df['sector'] == 'trn_freight_road')]

,Units,scenario,region,sector,subsector,Year,technology,value
250,None Specified,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,2035,BEV,0.571429
251,None Specified,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,2035,FCEV,0.235294
252,None Specified,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,2035,Liquids,0.333333

In [64]:
df[(df['Year'] == 2035) & (df['sector'] == 'trn_pass_road_LDV_4W')]

,Units,scenario,region,sector,subsector,Year,technology,value
681,None Specified,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Car,2035,BEV,0.571429
682,None Specified,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Car,2035,FCEV,0.235294
683,None Specified,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Car,2035,Hybrid Liquids,0.333333
684,None Specified,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Car,2035,Liquids,0.333333
685,None Specified,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Car,2035,NG,0.001004
774,None Specified,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2035,BEV,0.571429
775,None Specified,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2035,FCEV,0.235294
776,None Specified,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2035,Hybrid Liquids,0.333333
777,None Specified,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2035,Liquids,0.333333
778,None Specified,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2035,NG,0.001143

In [65]:
i = 159
q = queries[i]
title = q.title
print(title)
df = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
df['scenario'] = df['scenario'].str.split(',').str[0]
df

transport service output by tech

,Units,scenario,region,sector,subsector,technology,Year,value
0,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,BEV,2035,3.361960e-03
1,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Hydrogen,2035,1.042240e-03
2,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Liquids,1975,6.166440e+02
3,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Liquids,1990,4.066310e+03
4,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Liquids,2005,6.792510e+03
...,...,...,...,...,...,...,...,...
549,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2015,3.207670e+06
550,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2020,3.167640e+06
551,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2025,3.031810e+06
552,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2030,2.306920e+06
553,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2035,1.551620e+06

In [66]:
df['ZEV'] = df['technology'].apply(lambda tech: 1 if tech in ['BEV', 'FCEV'] else 0)
df

,Units,scenario,region,sector,subsector,technology,Year,value,ZEV
0,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,BEV,2035,3.361960e-03,1
1,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Hydrogen,2035,1.042240e-03,0
2,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Liquids,1975,6.166440e+02,0
3,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Liquids,1990,4.066310e+03,0
4,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Liquids,2005,6.792510e+03,0
...,...,...,...,...,...,...,...,...,...
549,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2015,3.207670e+06,0
550,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2020,3.167640e+06,0
551,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2025,3.031810e+06,0
552,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2030,2.306920e+06,0
553,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2035,1.551620e+06,0

In [67]:
df[(df['ZEV'] == 1)]['subsector'].unique()

array(['International Aviation', 'Domestic Aviation', 'Bus', '2W and 3W',
       'Car', 'Large Car and Truck', 'Domestic Ship', 'Freight Rail',
       'Medium truck', 'International Ship'], dtype=object)

In [68]:
lstServiceSectors = ['Bus', 'Car', 'Large Car and Truck', 'Medium truck']

In [69]:
df[(df['subsector'].isin(lstServiceSectors)) & (df['ZEV']==1) & (df['Year'] == 2030)]

,Units,scenario,region,sector,subsector,technology,Year,value,ZEV
78,million pass-km,Current-Policy,South Korea,trn_pass_road,Bus,BEV,2030,76947.8000,1
82,million pass-km,Current-Policy,South Korea,trn_pass_road,Bus,FCEV,2030,29788.7000,1
136,million pass-km,Current-Policy,South Korea,trn_pass_road_LDV_4W,Car,BEV,2030,29331.6560,1
140,million pass-km,Current-Policy,South Korea,trn_pass_road_LDV_4W,Car,FCEV,2030,437.6401,1
164,million pass-km,Current-Policy,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,BEV,2030,15414.2330,1
168,million pass-km,Current-Policy,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,FCEV,2030,169.9884,1
268,million pass-km,Enhanced-Ambition,South Korea,trn_pass_road,Bus,BEV,2030,165545.0000,1
272,million pass-km,Enhanced-Ambition,South Korea,trn_pass_road,Bus,FCEV,2030,58223.3000,1
322,million pass-km,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Car,BEV,2030,45180.9460,1
326,million pass-km,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Car,FCEV,2030,807.1841,1
350,million pass-km,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,BEV,2030,22063.3030,1
354,million pass-km,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,FCEV,2030,259.6402,1
434,million ton-km,Current-Policy,South Korea,trn_freight_road,Medium truck,BEV,2030,7392.0800,1
438,million ton-km,Current-Policy,South Korea,trn_freight_road,Medium truck,FCEV,2030,10844.3450,1
525,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,BEV,2030,13324.7600,1
529,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,FCEV,2030,34822.4850,1

In [70]:
dfService = df[(df['subsector'].isin(lstServiceSectors))].copy()
serServiceZev = dfService[(dfService['Year'] >= 2020) & (dfService['ZEV'] == 1)].groupby(['scenario', 'Year', 'Units'])['value'].sum()
serServiceTot = dfService[(dfService['Year'] >= 2020)].groupby(['scenario', 'Year', 'Units'])['value'].sum()
dfServiceRatio = (serServiceZev / serServiceTot).reset_index()
dfServiceRatio

             scenario  Year            Units     value
0      Current-Policy  2020  million pass-km  0.004787
1      Current-Policy  2020   million ton-km  0.010919
2      Current-Policy  2025  million pass-km  0.095868
3      Current-Policy  2025   million ton-km  0.050962
4      Current-Policy  2030  million pass-km  0.160690
5      Current-Policy  2030   million ton-km  0.084755
6      Current-Policy  2035  million pass-km  0.222436
7      Current-Policy  2035   million ton-km  0.129673
8   Enhanced-Ambition  2020  million pass-km  0.004792
9   Enhanced-Ambition  2020   million ton-km  0.010886
10  Enhanced-Ambition  2025  million pass-km  0.138506
11  Enhanced-Ambition  2025   million ton-km  0.074389
12  Enhanced-Ambition  2030  million pass-km  0.301770
13  Enhanced-Ambition  2030   million ton-km  0.218836
14  Enhanced-Ambition  2035  million pass-km  0.491844
15  Enhanced-Ambition  2035   million ton-km  0.410776

In [71]:
dfService[(dfService['Year'] == 2030) & (df['ZEV'] == 1)]#.groupby(['scenario', 'subsector'])['value'].sum()

/tmp/ipykernel_37791/2762981623.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

,Units,scenario,region,sector,subsector,technology,Year,value,ZEV
78,million pass-km,Current-Policy,South Korea,trn_pass_road,Bus,BEV,2030,76947.8000,1
82,million pass-km,Current-Policy,South Korea,trn_pass_road,Bus,FCEV,2030,29788.7000,1
136,million pass-km,Current-Policy,South Korea,trn_pass_road_LDV_4W,Car,BEV,2030,29331.6560,1
140,million pass-km,Current-Policy,South Korea,trn_pass_road_LDV_4W,Car,FCEV,2030,437.6401,1
164,million pass-km,Current-Policy,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,BEV,2030,15414.2330,1
168,million pass-km,Current-Policy,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,FCEV,2030,169.9884,1
268,million pass-km,Enhanced-Ambition,South Korea,trn_pass_road,Bus,BEV,2030,165545.0000,1
272,million pass-km,Enhanced-Ambition,South Korea,trn_pass_road,Bus,FCEV,2030,58223.3000,1
322,million pass-km,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Car,BEV,2030,45180.9460,1
326,million pass-km,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Car,FCEV,2030,807.1841,1
350,million pass-km,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,BEV,2030,22063.3030,1
354,million pass-km,Enhanced-Ambition,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,FCEV,2030,259.6402,1
434,million ton-km,Current-Policy,South Korea,trn_freight_road,Medium truck,BEV,2030,7392.0800,1
438,million ton-km,Current-Policy,South Korea,trn_freight_road,Medium truck,FCEV,2030,10844.3450,1
525,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,BEV,2030,13324.7600,1
529,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,FCEV,2030,34822.4850,1

In [72]:
dfServiceZev = serServiceZev.reset_index()
dfServiceZev['value'] /= 1000

In [73]:
i = 161
q = queries[i]
title = q.title
print(title)
df = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
df['scenario'] = df['scenario'].str.split(',').str[0]
df

transport service output by tech (new)

,Units,scenario,region,sector,subsector,technology,Year,value
0,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,BEV,2035,3.361960e-03
1,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Hydrogen,2035,1.042240e-03
2,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Liquids,1975,6.166440e+02
3,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Liquids,1990,4.066310e+03
4,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Liquids,2005,6.792510e+03
...,...,...,...,...,...,...,...,...
549,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2015,3.207670e+06
550,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2020,3.167640e+06
551,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2025,3.031810e+06
552,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2030,2.306920e+06
553,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2035,1.551620e+06

In [74]:
df['ZEV'] = df['technology'].apply(lambda tech: 1 if tech in ['BEV', 'FCEV'] else 0)
df

,Units,scenario,region,sector,subsector,technology,Year,value,ZEV
0,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,BEV,2035,3.361960e-03,1
1,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Hydrogen,2035,1.042240e-03,0
2,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Liquids,1975,6.166440e+02,0
3,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Liquids,1990,4.066310e+03,0
4,million pass-km,Current-Policy,South Korea,trn_aviation_intl,International Aviation,Liquids,2005,6.792510e+03,0
...,...,...,...,...,...,...,...,...,...
549,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2015,3.207670e+06,0
550,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2020,3.167640e+06,0
551,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2025,3.031810e+06,0
552,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2030,2.306920e+06,0
553,million ton-km,Enhanced-Ambition,South Korea,trn_shipping_intl,International Ship,Liquids,2035,1.551620e+06,0

In [75]:
df[(df['scenario'] == scenarios[1]) & (df['Year'] >= 2025) & (df['Units'] == 'million ton-km') & (df['subsector'] == 'Medium truck')]

,Units,scenario,region,sector,subsector,technology,Year,value,ZEV
524,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,BEV,2025,2255.99,1
525,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,BEV,2030,10667.80,1
526,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,BEV,2035,22826.70,1
528,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,FCEV,2025,11507.40,1
529,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,FCEV,2030,26489.30,1
530,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,FCEV,2035,37530.60,1
536,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,Liquids,2025,68486.00,0
537,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,Liquids,2030,62746.80,0
538,million ton-km,Enhanced-Ambition,South Korea,trn_freight_road,Medium truck,Liquids,2035,38552.60,0

In [76]:
dfService = df[(df['subsector'].isin(lstServiceSectors))].copy()
serServiceZev = dfService[(dfService['Year'] >= 2020) & (dfService['ZEV'] == 1)].groupby(['scenario', 'Year', 'Units'])['value'].sum()
serServiceTot = dfService[(dfService['Year'] >= 2020)].groupby(['scenario', 'Year', 'Units'])['value'].sum()
dfServiceRatio = (serServiceZev / serServiceTot).reset_index()
dfServiceRatio['value'] *= 100

In [77]:
dfService[(dfService['Year'] == 2030) & (df['ZEV'] == 1)].groupby(['scenario', 'subsector'])['value'].sum()

/tmp/ipykernel_37791/965632739.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

scenario           subsector
Current-Policy     Bus                    106736.500
                   Car                     20496.004
                   Large Car and Truck     11838.552
                   Medium truck            10795.690
Enhanced-Ambition  Bus                    223768.300
                   Car                     36876.425
                   Large Car and Truck     18664.825
                   Medium truck            37157.100
Name: value, dtype: float64

In [78]:
dfServiceRatio

             scenario  Year            Units      value
0      Current-Policy  2020  million pass-km   0.667835
1      Current-Policy  2020   million ton-km   3.132798
2      Current-Policy  2025  million pass-km  12.602290
3      Current-Policy  2025   million ton-km  10.982389
4      Current-Policy  2030  million pass-km  18.719158
5      Current-Policy  2030   million ton-km  11.190979
6      Current-Policy  2035  million pass-km  24.188381
7      Current-Policy  2035   million ton-km  16.815087
8   Enhanced-Ambition  2020  million pass-km   0.668731
9   Enhanced-Ambition  2020   million ton-km   3.105915
10  Enhanced-Ambition  2025  million pass-km  18.208927
11  Enhanced-Ambition  2025   million ton-km  16.733729
12  Enhanced-Ambition  2030  million pass-km  36.569839
13  Enhanced-Ambition  2030   million ton-km  37.192842
14  Enhanced-Ambition  2035  million pass-km  56.526863
15  Enhanced-Ambition  2035   million ton-km  61.022506

In [79]:
# Assign consistent colors for scenarios
color_map = {
    scenarios[0]: '#00CC96',   # blue
    scenarios[1]: '#AB63FA'
}


# Create subplot layout with secondary_y enabled in the first plot
fig = make_subplots(
    rows=1,
    cols=2,
    subplot_titles=["Passenger", "Freight"],
    specs=[[{"secondary_y": True}, {"secondary_y": True}]]
)

# First y-axis: Total passenger km
dfServiceRatioPass = dfServiceRatio[dfServiceRatio['Units'] == 'million pass-km']
for scenario in scenarios:
    scenario_data = dfServiceRatioPass[dfServiceRatioPass['scenario'] == scenario]
    fig.add_trace(
        go.Scatter(
            x=scenario_data['Year'],
            y=scenario_data['value'],
            name=f"New Sales in {scenario} in scenario (%)",
            mode='lines+markers',
            line=dict(color=color_map[scenario]),
        ),
        row=1,
        col=1,
        secondary_y=False
    )

# Second y-axis (right): ZEV passenger km
dfServiceZevPass = dfServiceZev[dfServiceZev['Units'] == 'million pass-km']
for scenario in scenarios:
    scenario_data = dfServiceZevPass[dfServiceZevPass['scenario'] == scenario]
    fig.add_trace(
        go.Bar(
            x=scenario_data['Year'],
            y=scenario_data['value'],
            name=f"Total Service in {scenario} scenario",
            marker_color=color_map[scenario],
            opacity=0.5
        ),
        row=1,
        col=1,
        secondary_y=True
    )

# First y-axis: Total passenger km
dfServiceRatioFreight = dfServiceRatio[dfServiceRatio['Units'] == 'million ton-km']
for scenario in scenarios:
    scenario_data = dfServiceRatioFreight[dfServiceRatioFreight['scenario'] == scenario]
    fig.add_trace(
        go.Scatter(
            x=scenario_data['Year'],
            y=scenario_data['value'],
            name=f"New Sales in {scenario} in scenario (%)",
            mode='lines+markers',
            line=dict(color=color_map[scenario]),
            showlegend=False
        ),
        row=1,
        col=2,
        secondary_y=False
    )

# Second y-axis (right): ZEV passenger km
dfServiceZevFreight = dfServiceZev[dfServiceZev['Units'] == 'million ton-km']
for scenario in scenarios:
    scenario_data = dfServiceZevFreight[dfServiceZevFreight['scenario'] == scenario]
    fig.add_trace(
        go.Bar(
            x=scenario_data['Year'],
            y=scenario_data['value'],
            name=f"Total Service in {scenario} scenario",
            marker_color=color_map[scenario],
            opacity=0.5,
            showlegend=False
        ),
        row=1,
        col=2,
        secondary_y=True
    )

# Apply layout formatting again
fig.update_layout(
    height=500,
    width=800,
    # title_text="<b>Projected ZEV Penetrations of Korea through 2035</b>",
    # title_font_size=18,
    # title_x=0.5,
    barmode='group',
    yaxis_title='Million pass–km/ton–km',
    xaxis_title=None,
    plot_bgcolor='white',
    paper_bgcolor='white',
    font=dict(color='black'),
    legend=dict(bgcolor='white'),
)

# Subplot (1,1)
fig.update_yaxes(title_text="New Sales Share (%)", secondary_y=False, row=1, col=1)
fig.update_yaxes(title_text="billion pass-km", secondary_y=True, row=1, col=1)

# Subplot (1,2)
fig.update_yaxes(title_text="New Sales Share (%)", secondary_y=False, row=1, col=2)
fig.update_yaxes(title_text="billion ton-km", secondary_y=True, row=1, col=2)

fig.update_yaxes(tickformat=',d', row=1, col=1)
fig.update_yaxes(tickformat=',d', row=1, col=2)

fig.update_layout(
    legend=dict(
        x=0.5,
        y=-0.2,
        xanchor='center',
        yanchor='top',
        orientation='h',  # horizontal layout
        bgcolor='white',
        bordercolor='lightgray',
        borderwidth=1,
        font=dict(size=18),
    )
)

# adjust axis labels and ticks
fig.update_xaxes(title_font=dict(size=18), tickfont=dict(size=18))
fig.update_yaxes(title_font=dict(size=18), tickfont=dict(size=18))

# bump the subplot titles
fig.update_annotations(font=dict(size=21))

# (if you also set a main title earlier)
# fig.update_layout(title=dict(font=dict(size=25)))

fig.show()

In [55]:
q = queries[265]
print(q.title)
dfCO2 = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
dfCO2['scenario'] = dfCO2['scenario'].str.split(',').str[0]
dfCO2['GHG'] = 'CO2'
q = queries[273]
print(q.title)
dfNonCO2 = conn.runQuery(q, scenarios=scenarios, regions=['South Korea'])
dfNonCO2['scenario'] = dfNonCO2['scenario'].str.split(',').str[0]
dfGHG = pd.concat([dfCO2, dfNonCO2], axis=0)
dfGHG['emiss(MT)'] = dfGHG.apply(to_Mt, axis=1)
dfGHG['gwpAr5'] = dfGHG['GHG'].apply(lambda gas: GWP_AR5[gas] if gas in GWP_AR5 else np.nan)
dfGHG['MTCO2eq'] = dfGHG['emiss(MT)'] * dfGHG['gwpAr5']
dfGHG

CO2 emissions by tech (excluding resource production)
nonCO2 emissions by tech (excluding resource production)

,Units,scenario,region,sector,subsector,technology,Year,value,GHG,emiss(MT),gwpAr5,MTCO2eq
0,MTC,Current-Policy,South Korea,H2 central production,biomass,biomass to H2,2020,6.269090e-04,CO2,2.297031e-03,1.0,2.297031e-03
1,MTC,Current-Policy,South Korea,H2 central production,biomass,biomass to H2,2025,8.708390e-02,CO2,3.190805e-01,1.0,3.190805e-01
2,MTC,Current-Policy,South Korea,H2 central production,biomass,biomass to H2,2030,3.796370e-02,CO2,1.391012e-01,1.0,1.391012e-01
3,MTC,Current-Policy,South Korea,H2 central production,biomass,biomass to H2,2035,5.667964e-02,CO2,2.076775e-01,1.0,2.076775e-01
4,MTC,Current-Policy,South Korea,H2 central production,coal,coal chemical CCS,2025,2.497390e-10,CO2,9.150582e-10,1.0,9.150582e-10
...,...,...,...,...,...,...,...,...,...,...,...,...
34866,Tg,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,2015,1.603690e-05,SO2_2,1.603690e-05,NaN,NaN
34867,Tg,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,2020,1.753690e-05,SO2_2,1.753690e-05,NaN,NaN
34868,Tg,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,2025,1.827714e-05,SO2_2,1.827714e-05,NaN,NaN
34869,Tg,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,2030,2.392284e-05,SO2_2,2.392284e-05,NaN,NaN
34870,Tg,Enhanced-Ambition,South Korea,waste biomass for paper,biomass,biomass cogen,2035,3.785459e-05,SO2_2,3.785459e-05,NaN,NaN

In [56]:
dfGHG[(dfGHG['sector'].str.contains('trn')) & ~(dfGHG['sector'].isin(['trn_aviation_intl', 'trn_shipping_intl']))].groupby(['scenario', 'Year'])['MTCO2eq'].sum()

scenario           Year
Current-Policy     1975      5.872180
                   1990     44.603113
                   2005     94.562268
                   2010    100.853747
                   2015    113.308707
                   2020    119.009238
                   2025    114.580297
                   2030    107.286699
                   2035    100.886961
Enhanced-Ambition  1975      5.872180
                   1990     44.603113
                   2005     94.562268
                   2010    100.853747
                   2015    113.308707
                   2020    117.833813
                   2025    113.070604
                   2030     97.502092
                   2035     77.338637
Name: MTCO2eq, dtype: float64

In [57]:
dfEmissTrn = dfGHG[(dfGHG['sector'].str.contains('trn')) & ~(dfGHG['sector'].isin(['trn_aviation_intl', 'trn_shipping_intl'])) & (dfGHG['Year'] >= 2020)].groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['MTCO2eq'].sum().reset_index()
dfEmissTrn

,scenario,Year,sector,subsector,technology,MTCO2eq
0,Current-Policy,2020,trn_freight,Domestic Ship,Hybrid Liquids,0.030645
1,Current-Policy,2020,trn_freight,Domestic Ship,Liquids,0.637189
2,Current-Policy,2020,trn_freight,Freight Rail,Liquids,0.340664
3,Current-Policy,2020,trn_freight_road,Medium truck,Hybrid Liquids,0.955374
4,Current-Policy,2020,trn_freight_road,Medium truck,Liquids,28.018624
...,...,...,...,...,...,...
129,Enhanced-Ambition,2035,trn_pass_road_LDV_4W,Car,Liquids,8.859169
130,Enhanced-Ambition,2035,trn_pass_road_LDV_4W,Car,NG,0.012290
131,Enhanced-Ambition,2035,trn_pass_road_LDV_4W,Large Car and Truck,Hybrid Liquids,4.828800
132,Enhanced-Ambition,2035,trn_pass_road_LDV_4W,Large Car and Truck,Liquids,8.935522
133,Enhanced-Ambition,2035,trn_pass_road_LDV_4W,Large Car and Truck,NG,0.012722

In [58]:
dfEmissTrn[(dfEmissTrn['Year'] == 2035)]

,scenario,Year,sector,subsector,technology,MTCO2eq
53,Current-Policy,2035,trn_freight,Domestic Ship,Hybrid Liquids,0.596959
54,Current-Policy,2035,trn_freight,Domestic Ship,Liquids,0.238506
55,Current-Policy,2035,trn_freight,Freight Rail,Hybrid Liquids,0.109469
56,Current-Policy,2035,trn_freight,Freight Rail,Liquids,0.194806
57,Current-Policy,2035,trn_freight_road,Medium truck,Hybrid Liquids,10.713892
58,Current-Policy,2035,trn_freight_road,Medium truck,Liquids,18.275486
59,Current-Policy,2035,trn_pass,Domestic Aviation,Liquids,17.270660
60,Current-Policy,2035,trn_pass,Passenger Rail,Liquids,0.669482
61,Current-Policy,2035,trn_pass_road,Bus,Hybrid Liquids,6.907042
62,Current-Policy,2035,trn_pass_road,Bus,Liquids,8.656362
63,Current-Policy,2035,trn_pass_road,Bus,NG,1.194920
64,Current-Policy,2035,trn_pass_road_LDV,2W and 3W,Liquids,0.462634
65,Current-Policy,2035,trn_pass_road_LDV_4W,Car,Hybrid Liquids,5.720435
66,Current-Policy,2035,trn_pass_road_LDV_4W,Car,Liquids,12.428378
67,Current-Policy,2035,trn_pass_road_LDV_4W,Car,NG,0.010855
68,Current-Policy,2035,trn_pass_road_LDV_4W,Large Car and Truck,Hybrid Liquids,5.350551
69,Current-Policy,2035,trn_pass_road_LDV_4W,Large Car and Truck,Liquids,12.076193
70,Current-Policy,2035,trn_pass_road_LDV_4W,Large Car and Truck,NG,0.010330
118,Enhanced-Ambition,2035,trn_freight,Domestic Ship,Hybrid Liquids,0.585154
119,Enhanced-Ambition,2035,trn_freight,Domestic Ship,Liquids,0.187172
120,Enhanced-Ambition,2035,trn_freight,Freight Rail,Hybrid Liquids,0.098827
121,Enhanced-Ambition,2035,trn_freight,Freight Rail,Liquids,0.174580
122,Enhanced-Ambition,2035,trn_freight_road,Medium truck,Liquids,20.649021
123,Enhanced-Ambition,2035,trn_pass,Domestic Aviation,Liquids,16.670166
124,Enhanced-Ambition,2035,trn_pass,Passenger Rail,Liquids,0.678884
125,Enhanced-Ambition,2035,trn_pass_road,Bus,Liquids,7.099042
126,Enhanced-Ambition,2035,trn_pass_road,Bus,NG,3.023011
127,Enhanced-Ambition,2035,trn_pass_road_LDV,2W and 3W,Liquids,0.451915
128,Enhanced-Ambition,2035,trn_pass_road_LDV_4W,Car,Hybrid Liquids,5.072364
129,Enhanced-Ambition,2035,trn_pass_road_LDV_4W,Car,Liquids,8.859169
130,Enhanced-Ambition,2035,trn_pass_road_LDV_4W,Car,NG,0.012290
131,Enhanced-Ambition,2035,trn_pass_road_LDV_4W,Large Car and Truck,Hybrid Liquids,4.828800
132,Enhanced-Ambition,2035,trn_pass_road_LDV_4W,Large Car and Truck,Liquids,8.935522
133,Enhanced-Ambition,2035,trn_pass_road_LDV_4W,Large Car and Truck,NG,0.012722