In [38]:
import gcamreader
import os
import sys
import subprocess
import pandas as pd
import pickle
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import xml.etree.ElementTree as ET
from pathlib import Path
from xml.dom import minidom
from itertools import product
# Get the parent directory of the current notebook
parent_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

# Add the parent directory to sys.path
sys.path.append(parent_dir)
from utils import catTech, string_to_xml_file, custom_colors, stack_order, ej_to_twh, convert_to_mt, classify_ghg, gwpAr5

# Korea's Regulation to Promote Zero Energy Buildings

A ZEB Regulation adopted for new buildings. Public buildings should achieve energy self-sufficiency rate(ESSR) at least 20% for 2023, 40% for 2025, 60% for 2030. For year 2020, this regulation was applied only for buildings with floorspace more than 500m^2. Scenario adopts ZEB from year 2025 and we assume that after 2030, 60% requirement is applied. Private buildings with floorspace more than 1,000 m^2 should achieve 20% of ESSR in 2025. After 2030 the requirement is applied to ones with floor space more than 500 m^2.

We model ZEB regulation by two steps: 1. calculate the total floor space required to attain full energy self-sufficiency. For example if a building with floor space 1000 m^2 attains 30% of ESSR, then we regard a building with floor space 300 m^2 attains full sufficiency. 2. We use unit energy consumption EJ/m^2 to calculate how much energy is needed. In GCAM, we assume energy is supplied by rooftop PV technology.

We refer two external dataset `/ext/240417(별첨)_23년_기준_건축_인허가_통계(건축정책과).xlsx` and `ext/240417(별첨)_23년_기준_건축물_현황_통계(건축정책과).xlsx` for estimation.

## Step 1 ZEB Buildings Share

In [8]:
tot_pr_floor_space = 4227660684.322 - 376645408.432
new_pr_floor_space = 147394196.42337 - 9195076.7802
new_pr_ratio = new_pr_floor_space / tot_pr_floor_space
new_pr_ratio

0.035886411697297435

In [ ]:
fs_gt_1000_share = 0.07369
fs_gt_500_share = 0.15460
ss_ratio_g5 = 0.2
new_pr_ratio_ss_25 = fs_gt_1000_share * new_pr_ratio * ss_ratio_g5 * 5
new_pr_ratio_ss_30 = new_pr_ratio_ss_25 + (new_pr_ratio * fs_gt_500_share) * ss_ratio_g5 * 5
new_pr_ratio_ss_35 = new_pr_ratio_ss_30 + (new_pr_ratio * fs_gt_500_share) * ss_ratio_g5 * 5
new_pr_ratio_ss_40 = new_pr_ratio_ss_35 + (new_pr_ratio * fs_gt_500_share) * ss_ratio_g5 * 5
print(new_pr_ratio_ss_25, new_pr_ratio_ss_30, new_pr_ratio_ss_35, new_pr_ratio_ss_40)

0.002644469677973848 0.00819250892637603 0.013740548174778214 0.019288587423180396

In [ ]:
fs_gt_500_share = 0.15460
ss_ratio = 0.2
private_vals = [fs_gt_1000_share * new_pr_ratio, fs_gt_500_share * ss_ratio, fs_gt_500_share * ss_ratio, fs_gt_500_share * ss_ratio]

In [10]:
tot_public_floor_space = 376645408.432
new_public_floor_space = 9195076.7802
new_public_ratio = new_public_floor_space / tot_public_floor_space
new_public_ratio

0.0244130860866716

In [12]:
ss_ratio_25 = 0.4
ss_ratio_30 = 0.6
new_public_ratio_ss_25 = fs_gt_500_share * new_public_ratio * ss_ratio_25 * 5
new_public_ratio_ss_30 = new_public_ratio_ss_25 + (fs_gt_500_share * ss_ratio_30 * new_public_ratio) * 5
new_public_ratio_ss_35 = new_public_ratio_ss_30 + (fs_gt_500_share * ss_ratio_30 * new_public_ratio) * 5
new_public_ratio_ss_40 = new_public_ratio_ss_35 + (fs_gt_500_share * ss_ratio_30 * new_public_ratio) * 5
print(new_public_ratio_ss_25, new_public_ratio_ss_30, new_public_ratio_ss_35, new_public_ratio_ss_40)

0.007548526217998858 0.018871315544997148 0.030194104871995437 0.04151689419899372

In [12]:
public_vals = [ss_ratio_25, ss_ratio_30, ss_ratio_30, ss_ratio_30]

In [13]:
pr_share = 0.911
serZebShare = pd.Series([
    new_pr_ratio_ss_25 * pr_share + new_public_ratio_ss_25 * (1-pr_share),
    new_pr_ratio_ss_30 * pr_share + new_public_ratio_ss_30 * (1-pr_share),
    new_pr_ratio_ss_35 * pr_share + new_public_ratio_ss_35 * (1-pr_share),
    new_pr_ratio_ss_40 * pr_share + new_public_ratio_ss_40 * (1-pr_share),
], index=[2025, 2030, 2035, 2040])
serZebShare

2025    0.003081
2030    0.009143
2035    0.015205
2040    0.021267
dtype: float64

## Unit Energy Demand

In [14]:
proj_path = Path("/data/project/tae/gcam-core")
xml_path = proj_path / "input" / "gcamdata" / "xml"
db_path = proj_path / "output"

In [15]:
db_file = "database_basexdb"
query_file = db_path / "queries" / "Main_queries.xml"
conn = gcamreader.LocalDBConn(db_path, db_file)
queries = gcamreader.parse_batch_query(query_file)

Database scenarios: Reference

In [16]:
for i, q in enumerate(queries):
    print(i, q.title)

0 primary energy consumption by region (avg fossil efficiency)
1 primary energy consumption by region (direct equivalent)
2 primary energy consumption with CCS by region (direct equivalent)
3 resource production
4 resource production by tech and vintage
5 resource supply curves
6 regional primary energy prices
7 elec gen by region (incl CHP)
8 elec gen by subsector
9 elec gen by gen tech
10 elec gen by gen tech and cooling tech
11 elec gen by gen tech and cooling tech and vintage
12 elec gen by gen tech and cooling tech (new)
13 elec energy input by subsector
14 elec energy input by elec gen tech
15 elec energy input by elec gen tech and cooling tech
16 elec prices by sector
17 elec gen costs by subsector
18 elec gen costs by tech
19 elec gen costs by cooling tech
20 elec share-weights by subsector
21 elec share-weights by tech
22 elec share-weights by cooling tech
23 elec td inputs and outputs
24 cogeneration by region
25 elec consumption by demand sector
26 elec sector water withdrawals
27 elec sector water consumption
28 elec water withdrawals by gen tech
29 elec water consumption by gen tech
30 elec water withdrawals by gen tech and cooling tech
31 elec water consumption by gen tech and cooling tech
32 elec water withdrawals by gen tech and cooling tech (new)
33 elec water consumption by gen tech and cooling tech (new)
34 refined liquids production by region
35 refined liquids production by subsector
36 refined liquids production by tech
37 refined liquids production by tech and vintage
38 refined liquids production by tech (new)
39 refinery inputs by tech (energy and feedstocks)
40 refined liquids prices by sector
41 refined liquids costs by subsector
42 refined liquids costs by tech
43 refining and oil share-weights by subsector
44 refining share-weights by tech
45 hydrogen production by tech
46 hydrogen inputs by tech
47 hydrogen prices by sector
48 hydrogen costs by tech
49 hydrogen technology IO coefficients
50 hydrogen utilization by technology
51 hydrogen non-energy costs
52 hydrogen outputs by technology
53 hydrogen dispensing energy by primary fuel
54 gas production by tech
55 gas production share-weights by subsector
56 gas inputs by tech (energy and feedstocks)
57 gas pipeline inputs and outputs
58 gas prices by sector
59 gas costs by tech
60 gas consumption by sector
61 delivered gas energy by primary fuel
62 district heat production by subsector (fuel)
63 district heat energy inputs by subsector
64 total final energy by region
65 total final energy by aggregate sector
66 total final energy by sector
67 final energy consumption by fuel
68 final energy consumption by sector and fuel
69 final energy prices
70 building floorspace
71 building floorspace per capita
72 building commercial floorspace satiation impedance
73 building residential floorspace regional bias adder
74 building total final energy by region
75 building total final energy by service
76 building final energy by fuel
77 building final energy by service and fuel
78 building final energy by subsector
79 building final energy by tech
80 building final energy by tech and vintage
81 building final energy by tech (new)
82 building service output by service
83 building service output by subsector
84 building service output by tech
85 building service output by tech and vintage
86 building service output by tech (new)
87 building service density by energy service
88 building satiation impedance by energy service
89 building regional bias adder by energy service
90 building internal gain energy by service
91 total service cost per unit floorspace
92 building service costs
93 fuel prices to buildings
94 building share-weights by subsector
95 building share-weights by tech
96 industry total final energy by region
97 industry total final energy by service
98 industry final energy by fuel
99 industry final energy by service and fuel
100 industry final energy by tech and fuel
101 industry feedstocks by type
102 industry primary output by sector
103 industry cogeneration by fuel
104 fuel prices to industry
105 industry share-weights by subsector
106 industry water withdrawals and consumption
107 cement production by region
108 cement production by tech (conv and ccs)
109 cement production by tech and vintage
110 inputs to cement production
111 cement prices
112 ammonia production by region
113 ammonia production by tech
114 ammonia inputs by tech (energy and feedstocks)
115 ammonia and N fertilizer prices
116 ammonia domestic supply
117 ammonia exports (query USA region)
118 iron and steel production by region
119 iron and steel production by tech
120 iron and steel production by tech and vintage
121 iron and steel inputs by tech (energy and feedstocks)
122 iron and steel prices
123 traded iron and steel
124 regional iron and steel sources
125 chemical production by region
126 chemical inputs by tech (energy and feedstocks)
127 chemical prices
128 aluminum production by region
129 aluminum production by tech
130 aluminum production by tech and vintage
131 aluminum inputs by tech (energy and feedstocks)
132 aluminum prices
133 construction inputs (energy and feedstocks)
134 agricultural energy use
135 mining energy use
136 food processing production by region
137 food processing process heat production by tech
138 inputs to food processing
139 inputs to food processing (process heat separated)
140 food processing prices
141 paper production by region
142 inputs to paper production
143 paper prices
144 energy-for-water TFE
145 energy-for-water FE by fuel
146 energy-for-water FE by process and fuel
147 prices of energy-for-water processes
148 water flow volumes of EFW processes
149 nonrenewable groundwater pumping energy
150 transport total final energy by region
151 transport total final energy by service
152 transport final energy by fuel
153 transport final energy by mode and fuel
154 transport final energy by tech and fuel
155 transport final energy by tech and vintage
156 transport final energy by tech (new)
157 transport service output by service
158 transport service output by mode
159 transport service output by tech
160 transport service output by tech and vintage
161 transport service output by tech (new)
162 transport load factors
163 fuel prices to transport
164 costs of transport services
165 costs of transport modes
166 costs of transport techs
167 transport tech non-energy cost
168 LDV energy by primary fuel
169 transport subsector share-weights
170 transport tech share-weights
171 transport speeds
172 building final energy by tech
173 building service output by tech
174 building floorspace
175 industry final energy by service and fuel
176 transport final energy by tech and fuel
177 transport final energy by tech (new)
178 transport service output by tech
179 transport service output by tech (new)
180 detailed land allocation
181 detailed historical land allocation
182 land allocation by crop
183 aggregated land allocation
184 aggregated historical land allocation
185 land allocation in a specified land use region
186 land allocation by crop and water source
187 LUC emissions by region
188 LUC emissions by LUT
189 LUC emissions by LUT in a specified land use region
190 vegetative carbon stock by region
191 profit rate
192 profit rate in a specified land use region
193 land leaf shares
194 land leaf shares in a specified land use region
195 ag production by crop type
196 ag production by subsector (land use region)
197 ag production in a specified land use region
198 ag production by tech
199 ag tech variable cost
200 ag tech yield
201 ag tech yield in a specified land region
202 ag commodity prices
203 ag tech implied subsidy
204 irrigation water withdrawals by region
205 irrigation water withdrawals by crop type
206 irrigation water withdrawals by crop type and land region
207 irrigation water withdrawals by ag tech
208 irrigation water consumption by region
209 irrigation water consumption by crop type
210 irrigation water consumption by crop type and land region
211 irrigation water consumption by ag tech
212 biophysical water demand by region
213 biophysical water demand by crop type
214 biophysical water demand by crop type and land region
215 biophysical water demand by ag tech
216 fertilizer consumption by region
217 fertilizer consumption by crop type
218 fertilizer consumption by ag tech
219 fertilizer-crop input-output coefficients
220 purpose-grown biomass production
221 residue biomass production
222 MSW production
223 regional biomass consumption
224 meat and dairy production by type
225 meat and dairy production by tech
226 meat and dairy prices
227 meat and dairy subsector share-weights
228 meat and dairy tech share-weights
229 meat and dairy subsector costs
230 meat and dairy tech costs
231 water consumption by meat and dairy production
232 feed consumption by region
233 feed consumption by meat and dairy tech
234 feed sources
235 feed prices
236 feed subsector share-weights
237 food consumption by type (general)
238 food consumption by type (specific)
239 demand balances by crop commodity
240 demand balances by meat and dairy commodity
241 food demand prices
242 food demand
243 food demand per capita
244 food demand regional bias
245 ag import vs. domestic supply (Regional Armington competition)
246 ag export to the world center (USA) (Intl. Armington competition)
247 ag import vs. domestic prices
248 ag export prices (at world center USA)
249 import vs. domestic share-weights (Armington regional taste)
250 international competition share-weights (Armington intl. taste)
251 ag total prices (weighted average b/t domestic and imported prices)
252 opening stocks (supply from carryover)
253 closing stocks (before loss/adjustments)
254 closing stocks (after loss/adjustments; carried over)
255 current supply (current or regional consumption)
256 ag regional prices (current consumer prices)
257 agricultural storage share-weights
258 storage cost
259 expected price
260 CO2 emissions by region
261 CO2 emissions by sector (excluding resource production)
262 CO2 emissions by sector (no bio) (excluding resource production)
263 CO2 emissions by assigned sector (no bio) (excluding resource production)
264 CO2 emissions by subsector (excluding resource production)
265 CO2 emissions by tech (excluding resource production)
266 CO2 emissions by resource production
267 CO2 sequestration by sector
268 CO2 sequestration by tech
269 nonCO2 emissions by region
270 nonCO2 emissions by sector (excluding resource production)
271 nonCO2 emissions by resource production
272 nonCO2 emissions by subsector (excluding resource production)
273 nonCO2 emissions by tech (excluding resource production)
274 specific nonCO2 emissions by region
275 specific nonCO2 emissions by sector (excluding resource production)
276 specific nonCO2 emissions by resource production
277 specific nonCO2 emissions by subsector (excluding resource production)
278 specific nonCO2 emissions by tech (excluding resource production)
279 CO2 concentrations
280 total climate forcing
281 global mean temperature
282 net terrestrial C uptake
283 population by region
284 GDP MER by region
285 GDP per capita MER by region
286 GDP per capita PPP by region
287 subregional population
288 subregional income
289 National Account
290 Social Accounting Matrix
291 Tracking accounts by tech
292 Capital investment demands by tech
293 Capital investment demands by resource
294 CO2 prices
295 policy cost by period
296 undiscounted policy cost
297 discounted policy cost
298 regional CO2 MAC curves by period
299 water withdrawals by region
300 water withdrawals by water mapping source
301 water withdrawals by sector
302 water withdrawals by subsector
303 water withdrawals by tech
304 water consumption by region
305 water consumption by water mapping source
306 water consumption by sector
307 water consumption by subsector
308 water consumption by tech
309 Basin level available runoff
310 Water withdrawals by water source (runoff vs. groundwater)
311 Water Withdrawals by Basin (Runoff)
312 Water Withdrawals by Basin (Groundwater)
313 Cumulative groundwater extraction
314 prices of all markets
315 supply of all markets
316 demand of all markets
317 price of a specific market
318 supply of a specific market
319 prices by sector
320 costs by subsector
321 costs by tech
322 costs by tech and input
323 inputs by sector
324 inputs by subsector
325 inputs by tech
326 outputs by sector
327 outputs by subsector
328 outputs by tech
329 input-output coefficients by tech
330 primary energy consumption by region (direct equivalent)
331 industry water withdrawals and consumption
332 elec gen by region (no CHP)
333 elec gen by subsector
334 elec gen by gen tech (cogen only)
335 elec gen by gen tech and cooling tech (incl cogen)
336 elec energy input by subsector
337 elec energy input by elec gen tech
338 elec prices by sector
339 elec gen costs by subsector
340 elec gen costs by tech
341 elec share-weights by subsector
342 elec share-weights by gen tech
343 elec share-weights by cooling tech
344 elec water withdrawals by gen tech and cooling tech
345 elec water consumption by gen tech and cooling tech
346 refined liquids production by region
347 refined liquids production by subsector
348 refined liquids production by tech
349 refined liquids production by tech and vintage
350 refined liquids production by tech (new)
351 refinery inputs by tech (energy and feedstocks)
352 refined liquids prices by sector
353 refined liquids costs by subsector
354 refined liquids costs by tech
355 refining and oil share-weights by subsector
356 refining share-weights by tech
357 total final energy by aggregate sector
358 water withdrawals by state, sector, basin
359 water withdrawals by state, sector, basin (includes desal)
360 water consumption by state, sector, basin
361 water consumption by state, sector, basin (includes desal)
362 CO2 emissions by tech (nested subsector) (excluding resource production)
363 CO2 sequestration by tech (nested subsector)

In [17]:
q = queries[70]
print(q.title)
dfFloor = conn.runQuery(query=q, scenarios=['Reference'], regions=['South Korea'])
dfFloor['scenario'] = dfFloor['scenario'].str.split(',').str[0]
dfFloor.head()

building floorspace

,Units,scenario,region,building,nodeInput,building-node-input,Year,value
0,billion m^2,Reference,South Korea,comm,comm,comm_building,1975,0.333635
1,billion m^2,Reference,South Korea,comm,comm,comm_building,1990,0.489230
2,billion m^2,Reference,South Korea,comm,comm,comm_building,2005,0.677551
3,billion m^2,Reference,South Korea,comm,comm,comm_building,2010,0.689301
4,billion m^2,Reference,South Korea,comm,comm,comm_building,2015,0.707074

In [18]:
q = queries[77]
print(q.title)
dfEnergy = conn.runQuery(query=q, scenarios=['Reference'], regions=['South Korea'])
dfEnergy['nodeInput'] = dfEnergy['sector'].apply(lambda s: 'comm' if s.startswith('comm') else 'resid')
dfEnergy['scenario'] = dfEnergy['scenario'].str.split(',').str[0]
dfEnergy.head()

building final energy by service and fuel

,Units,scenario,region,sector,input,Year,value,nodeInput
0,EJ,Reference,South Korea,comm cooling,delivered gas,1990,0.000386,comm
1,EJ,Reference,South Korea,comm cooling,delivered gas,2005,0.008490,comm
2,EJ,Reference,South Korea,comm cooling,delivered gas,2010,0.009812,comm
3,EJ,Reference,South Korea,comm cooling,delivered gas,2015,0.010216,comm
4,EJ,Reference,South Korea,comm cooling,delivered gas,2020,0.009217,comm

In [19]:
# final energy consumption by floorspace: comm
denon = dfFloor[(dfFloor['Year'] >= 2025) & (dfFloor['Year'] <= 2040)].groupby(['scenario', 'region', 'Year'])['value'].sum()
num = dfEnergy[(dfEnergy['Year'] >= 2025) & (dfEnergy['Year'] <= 2040)].groupby(['scenario', 'region', 'Year'])['value'].sum()
enConUnit = num / denon
enConUnit.index = range(2025, 2045, 5)
enConUnit

2025    0.882254
2030    0.895309
2035    0.897442
2040    0.892007
Name: value, dtype: float64

## 3. Floor Space Tot

In [20]:
serFloor = dfFloor[dfFloor['Year'].isin([2025, 2030, 2035, 2040])].groupby(['Year'])['value'].sum()
serFloor

Year
2025    2.079178
2030    2.150664
2035    2.193658
2040    2.209648
Name: value, dtype: float64

In [21]:
zebTarget = serFloor * serZebShare * enConUnit
zebTarget

Year
2025    0.005652
2030    0.017605
2035    0.029934
2040    0.041918
dtype: float64

## Rooftop PV Generation in the Reference Scenario

In [22]:
q = queries[9]
print(q.title)
dfGen = conn.runQuery(query=q, scenarios=['Reference'], regions=['South Korea'])
dfGen['scenario'] = dfGen['scenario'].str.split(',').str[0]
dfGen.head()

elec gen by gen tech

,Units,scenario,region,subsector,technology,output,Year,value
0,EJ,Reference,South Korea,biomass,biomass (IGCC),electricity,2025,0.000417
1,EJ,Reference,South Korea,biomass,biomass (IGCC),electricity,2030,0.001082
2,EJ,Reference,South Korea,biomass,biomass (IGCC),electricity,2035,0.002026
3,EJ,Reference,South Korea,biomass,biomass (IGCC),electricity,2040,0.003233
4,EJ,Reference,South Korea,biomass,biomass (IGCC),electricity,2045,0.004462

In [23]:
dfGen['technology'].unique()

array(['biomass (IGCC)', 'biomass (conv)', 'coal (IGCC)',
       'coal (conv pul)', 'gas (CC)', 'gas (steam/CT)', 'hydro',
       'Gen_III', 'Gen_II_LWR', 'refined liquids (CC)',
       'refined liquids (steam/CT)', 'rooftop_pv', 'CSP_storage', 'PV',
       'PV_storage', 'wind', 'wind_offshore', 'wind_storage'],
      dtype=object)

In [24]:
serRefGen = dfGen[(dfGen['Year'] >= 2020) & (dfGen['Year'] <= 2040) & (dfGen['technology'] == 'rooftop_pv')].groupby(['Year', 'scenario'])['value'].sum()
serRefGen.index = [2020, 2025, 2030, 2035, 2040]
serRefGen

2020    0.002308
2025    0.017475
2030    0.050636
2035    0.085309
2040    0.103447
Name: value, dtype: float64

In [25]:
roofTopGen = zebTarget + serRefGen
roofTopGen

2020         NaN
2025    0.023126
2030    0.068241
2035    0.115243
2040    0.145365
dtype: float64

We add the rooptop generation of South Korea in 2020 to the constraint.

```xml
<?xml version="1.0" ?>
<scenario>
  <world>
    <region name="South Korea">
      <policy-portfolio-standard name="ZEB-Certification-Target">
        <policyType>subsidy</policyType>
        <market>South Korea</market>
        <constraint year="2020">0.012</constraint>
        <constraint year="2025">0.030</constraint>
        <constraint year="2030">0.086</constraint>
        <constraint year="2035">0.144</constraint>
        <constraint year="2040">0.185</constraint>
      </policy-portfolio-standard>
    </region>
  </world>
</scenario>

```

## Enhanced Policy

Private buildings are regulated by the same condition for the public buildings after 2030

In [26]:
tot_pr_floor_space = 4227660684.322 - 376645408.432
new_pr_floor_space = 147394196.42337 - 9195076.7802
new_pr_ratio = new_pr_floor_space / tot_pr_floor_space
new_pr_ratio

0.035886411697297435

In [27]:
fs_gt_1000_share = 0.07369
fs_gt_500_share = 0.15460
ss_ratio = 0.2
ss_ratio_30 = 0.4
new_pr_ratio_ss_25 = fs_gt_1000_share * new_pr_ratio * ss_ratio * 5
new_pr_ratio_ss_30 = new_pr_ratio_ss_25 + (new_pr_ratio * fs_gt_500_share) * ss_ratio_30 * 5
new_pr_ratio_ss_35 = new_pr_ratio_ss_30 + (new_pr_ratio * fs_gt_500_share) * ss_ratio_30 * 5
new_pr_ratio_ss_40 = new_pr_ratio_ss_35 + (new_pr_ratio * fs_gt_500_share) * ss_ratio_30 * 5
print(new_pr_ratio_ss_25, new_pr_ratio_ss_30, new_pr_ratio_ss_35, new_pr_ratio_ss_40)

0.002644469677973848 0.013740548174778214 0.024836626671582582 0.035932705168386946

In [28]:
private_vals += [fs_gt_1000_share * new_pr_ratio, fs_gt_500_share * ss_ratio_30, fs_gt_500_share * ss_ratio_30, fs_gt_500_share * ss_ratio_30]

NameError: name 'private_vals' is not defined

In [29]:
tot_public_floor_space = 376645408.432
new_public_floor_space = 9195076.7802
new_public_ratio = new_public_floor_space / tot_public_floor_space
new_public_ratio

0.0244130860866716

In [34]:
ss_ratio_25 = 0.4
ss_ratio_30 = 0.6
new_public_ratio_ss_25 = fs_gt_500_share * new_public_ratio * ss_ratio_25 * 5
new_public_ratio_ss_30 = new_public_ratio_ss_25 + (fs_gt_500_share * ss_ratio_30 * new_public_ratio) * 5
new_public_ratio_ss_35 = new_public_ratio_ss_30 + (fs_gt_500_share * ss_ratio_30 * new_public_ratio) * 5
new_public_ratio_ss_40 = new_public_ratio_ss_35 + (fs_gt_500_share * ss_ratio_30 * new_public_ratio) * 5
print(new_public_ratio_ss_25, new_public_ratio_ss_30, new_public_ratio_ss_35, new_public_ratio_ss_40)

0.007548526217998858 0.018871315544997148 0.030194104871995437 0.04151689419899372

In [35]:
pr_share = 0.911
serZebShare = pd.Series([
    new_pr_ratio_ss_25 * pr_share + new_public_ratio_ss_25 * (1-pr_share),
    new_pr_ratio_ss_30 * pr_share + new_public_ratio_ss_30 * (1-pr_share),
    new_pr_ratio_ss_35 * pr_share + new_public_ratio_ss_35 * (1-pr_share),
    new_pr_ratio_ss_40 * pr_share + new_public_ratio_ss_40 * (1-pr_share),
], index=[2025, 2030, 2035, 2040])
serZebShare

2025    0.003081
2030    0.014197
2035    0.025313
2040    0.036430
dtype: float64

In [36]:
zebTarget = serFloor * serZebShare * enConUnit
zebTarget

Year
2025    0.005652
2030    0.027337
2035    0.049834
2040    0.071804
dtype: float64

In [37]:
roofTopGen = zebTarget + serRefGen
roofTopGen

2020         NaN
2025    0.023126
2030    0.077973
2035    0.135144
2040    0.175251
dtype: float64

```xml

<?xml version="1.0" ?>
<scenario>
  <world>
    <region name="South Korea">
      <policy-portfolio-standard name="ZEB-Certification-Target">
        <policyType>subsidy</policyType> 
        <market>South Korea</market>
        <constraint year="2020">0.012</constraint>
        <constraint year="2025">0.030</constraint>
        <constraint year="2030">0.096</constraint>
        <constraint year="2035">0.164</constraint>
        <constraint year="2040">0.215</constraint>
      </policy-portfolio-standard>
    </region>
  </world>
</scenario>
```

# Model Run

```xml
<?xml version="1.0" encoding="UTF-8"?>
<BatchRunner xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="batch_runner.xsd">

	<ComponentSet name="Policy">

		<FileSet name="_Reference">
		</FileSet>

		<FileSet name="_CurPol">
			<Value name="zeb">../input/policy/ndc/buildings/zeb_target_constraint.xml</Value>
			<Value name="zeb">../input/policy/ndc/buildings/zeb_target_tech.xml</Value>
		</FileSet>

		<FileSet name="_EnhPol">
			<Value name="zeb">../input/policy/ndc/buildings/zeb_target_constraint_EnhPol.xml</Value>
			<Value name="zeb">../input/policy/ndc/buildings/zeb_target_tech_EnhPol.xml</Value>
		</FileSet>

	</ComponentSet>

</BatchRunner>
```

In [159]:
config_ref_file_path = proj_path / "exe/configuration_ref.xml"
db_path = "../output/database_basexdb_test"
scen_name = "ZEB"
end_year = "2050"
batch_mode = "1"
batch_fn = "batch_test.xml"
config_test_file_path = proj_path / "exe/configuration_test.xml"


tree = ET.parse(config_ref_file_path)
root = tree.getroot()

# set db location
db_loc = root.find(".//Files/Value[@name='xmldb-location']")
db_loc.text = str(db_path)

# set db location
batch_file_name = root.find(".//Files/Value[@name='BatchFileName']")
batch_file_name.text = batch_fn

# set scenario name
scenario_name = root.find(".//Strings/Value[@name='scenarioName']")
scenario_name.text = scen_name

# turn on batch mode
batch_mode = root.find(".//Bools/Value[@name='BatchMode']")
batch_mode.text = "1"

# set stop-year
stop_year = root.find(".//Ints/Value[@name='stop-year']")
stop_year.text = end_year

# save
xml_string = ET.tostring(root, encoding="unicode")
string_to_xml_file(xml_string, config_test_file_path)

XML file '/data/project/tae/gcam-core/exe/configuration_test.xml' created successfully with proper indentation and no extra newlines.

In [161]:
os.chdir("../analyze/script-ndc/buildings")

In [177]:
# Change directory
os.chdir("../../../exe")

# Command to run
command = ["./gcam.exe", "-C", "configuration_test.xml"]

# Run the command and print logs in real-time
try:
    process = subprocess.Popen(
        command, 
        stdout=subprocess.PIPE, 
        stderr=subprocess.PIPE, 
        text=True
    )

    # Print stdout and stderr in real-time
    for line in process.stdout:
        print(line, end="")  # Print each line of stdout
    for line in process.stderr:
        print(line, end="")  # Print each line of stderr

    # Wait for the process to complete
    process.wait()

    # Check return code to see if the process was successful
    if process.returncode == 0:
        print("\nCommand executed successfully!")
    else:
        print("\nCommand failed!")
except Exception as e:
    print(f"An error occurred: {e}")

os.chdir("../analyze/script-ndc/buildings")

This computer software was prepared by Battelle Memorial Institute,
hereinafter the Contractor, under Contract No. DE-AC05-76RL0 1830 with
the Department of Energy (DOE). NEITHER THE GOVERNMENT NOR THE
CONTRACTOR MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY
LIABILITY FOR THE USE OF THIS SOFTWARE. This notice including this
sentence must appear on any copies of this computer software.

User agrees that the Software will not be shipped, transferred or
exported into any country or used in any manner prohibited by the United
States Export Administration Act or any other applicable export laws,
restrictions or regulations (collectively the 'Export Laws'). Export of
the Software may require some form of license or other authority from
the U.S. Government, and failure to obtain such export control license
may result in criminal liability under U.S. laws. In addition, if the
Software is identified as export controlled items under the Export Laws,
User represents and warrants that User is not a citizen, or otherwise
located within, an embargoed nation (including without limitation Iran,
Syria, Sudan, Cuba, and North Korea) and that User is not otherwise
prohibited under the Export Laws from receiving the Software.

Copyright 2011 Battelle Memorial Institute.  All Rights Reserved.
Distributed as open-source under the terms of the Educational Community
License version 2.0 (ECL 2.0). http://www.opensource.org/licenses/ecl2.php

For further details, see: http://www.globalchange.umd.edu/models/gcam/

Running GCAM model code base version 7.1 revision gcam-v7.1

Configuration file:  configuration_test.xml
Parsing input files...
Reading Batch File batch_test.xml
Running scenario _EnhPol with scenario runner single-scenario-runner.
Parsing ../input/gcamdata/xml/hector.xml scenario component.
Parsing ../input/gcamdata/xml/socioeconomics_gSSP2.xml scenario component.
Parsing ../input/gcamdata/xml/resources.xml scenario component.
Parsing ../input/gcamdata/xml/en_supply.xml scenario component.
Parsing ../input/gcamdata/xml/en_transformation.xml scenario component.
Parsing ../input/gcamdata/xml/electricity_water.xml scenario component.
Parsing ../input/gcamdata/xml/heat.xml scenario component.
Parsing ../input/gcamdata/xml/hydrogen.xml scenario component.
Parsing ../input/gcamdata/xml/en_distribution.xml scenario component.
Parsing ../input/gcamdata/xml/other_industry.xml scenario component.
Parsing ../input/gcamdata/xml/other_industry_incelas_gssp2.xml scenario component.
Parsing ../input/gcamdata/xml/iron_steel.xml scenario component.
Parsing ../input/gcamdata/xml/iron_steel_incelas_gssp2.xml scenario component.
Parsing ../input/gcamdata/xml/iron_steel_trade.xml scenario component.
Parsing ../input/gcamdata/xml/Off_road.xml scenario component.
Parsing ../input/gcamdata/xml/Off_road_incelas_gssp2.xml scenario component.
Parsing ../input/gcamdata/xml/chemical.xml scenario component.
Parsing ../input/gcamdata/xml/chemical_incelas_gssp2.xml scenario component.
Parsing ../input/gcamdata/xml/aluminum.xml scenario component.
Parsing ../input/gcamdata/xml/aluminum_incelas_gssp2.xml scenario component.
Parsing ../input/gcamdata/xml/paper.xml scenario component.
Parsing ../input/gcamdata/xml/paper_incelas_gssp2.xml scenario component.
Parsing ../input/gcamdata/xml/food_processing.xml scenario component.
Parsing ../input/gcamdata/xml/cement.xml scenario component.
Parsing ../input/gcamdata/xml/cement_incelas_gssp2.xml scenario component.
Parsing ../input/gcamdata/xml/en_Fert.xml scenario component.
Parsing ../input/gcamdata/xml/HDDCDD_constdd_no_GCM.xml scenario component.
Parsing ../input/gcamdata/xml/building_det.xml scenario component.
Parsing ../input/gcamdata/xml/transportation_UCD_CORE.xml scenario component.
Parsing ../input/gcamdata/xml/Ccoef.xml scenario component.
Parsing ../input/gcamdata/xml/Cstorage.xml scenario component.
Parsing ../input/gcamdata/xml/onshore_wind.xml scenario component.
Parsing ../input/gcamdata/xml/ag_For_Past_bio_base_IRR_MGMT.xml scenario component.
Parsing ../input/gcamdata/xml/ag_cost_IRR_MGMT.xml scenario component.
Parsing ../input/gcamdata/xml/ag_prodchange_ref_IRR_MGMT.xml scenario component.
Parsing ../input/gcamdata/xml/resbio_input_IRR_MGMT.xml scenario component.
Parsing ../input/gcamdata/xml/an_input.xml scenario component.
Parsing ../input/gcamdata/xml/ag_Fert_IRR_MGMT.xml scenario component.
Parsing ../input/gcamdata/xml/land_input_1.xml scenario component.
Parsing ../input/gcamdata/xml/land_input_2.xml scenario component.
Parsing ../input/gcamdata/xml/land_input_3_IRR.xml scenario component.
Parsing ../input/gcamdata/xml/land_input_4_IRR_MGMT.xml scenario component.
Parsing ../input/gcamdata/xml/land_input_5_IRR_MGMT.xml scenario component.
Parsing ../input/gcamdata/xml/protected_land_input_2.xml scenario component.
Parsing ../input/gcamdata/xml/protected_land_input_3.xml scenario component.
Parsing ../input/gcamdata/xml/ag_an_demand_input.xml scenario component.
Parsing ../input/gcamdata/xml/paper_delete_ag_demand.xml scenario component.
Parsing ../input/gcamdata/xml/bio_trade.xml scenario component.
Parsing ../input/gcamdata/xml/ag_trade.xml scenario component.
Parsing ../input/gcamdata/xml/ag_storage.xml scenario component.
Parsing ../input/gcamdata/xml/unlimited_water_supply.xml scenario component.
Parsing ../input/gcamdata/xml/water_supply_constrained.xml scenario component.
Parsing ../input/gcamdata/xml/desalination.xml scenario component.
Parsing ../input/gcamdata/xml/water_td.xml scenario component.
Parsing ../input/gcamdata/xml/EFW_input_coefs.xml scenario component.
Parsing ../input/gcamdata/xml/EFW_irrigation.xml scenario component.
Parsing ../input/gcamdata/xml/EFW_manufacturing.xml scenario component.
Parsing ../input/gcamdata/xml/EFW_municipal.xml scenario component.
Parsing ../input/gcamdata/xml/ag_water_input_IRR_MGMT.xml scenario component.
Parsing ../input/gcamdata/xml/electricity_water_coefs.xml scenario component.
Parsing ../input/gcamdata/xml/water_demand_industry.xml scenario component.
Parsing ../input/gcamdata/xml/water_demand_livestock.xml scenario component.
Parsing ../input/gcamdata/xml/water_demand_municipal.xml scenario component.
Parsing ../input/gcamdata/xml/water_demand_primary.xml scenario component.
Parsing ../input/gcamdata/xml/ind_urb_processing_sectors.xml scenario component.
Parsing ../input/gcamdata/xml/all_energy_emissions.xml scenario component.
Parsing ../input/gcamdata/xml/all_fgas_emissions.xml scenario component.
Parsing ../input/gcamdata/xml/all_unmgd_emissions.xml scenario component.
Parsing ../input/gcamdata/xml/all_aglu_emissions_IRR_MGMT.xml scenario component.
Parsing ../input/gcamdata/xml/all_protected_unmgd_emissions.xml scenario component.
Parsing ../input/gcamdata/xml/emission_factor_controls.xml scenario component.
Parsing ../input/gcamdata/xml/ssp2_emissions_factors_tradBio.xml scenario component.
Parsing ../input/gcamdata/xml/all_energy_emissions_MAC.xml scenario component.
Parsing ../input/gcamdata/xml/all_fgas_emissions_MAC.xml scenario component.
Parsing ../input/gcamdata/xml/all_aglu_emissions_IRR_MGMT_MAC.xml scenario component.
Parsing ../input/gcamdata/xml/ind_urb_processing_sectors_MAC.xml scenario component.
Parsing ../input/gcamdata/xml/socioeconomics_macro.xml scenario component.
Parsing ../input/gcamdata/xml/liquids_limits.xml scenario component.
Parsing ../input/gcamdata/xml/water_elec_liquids_limits.xml scenario component.
Parsing ../input/gcamdata/xml/bio_externality.xml scenario component.
Parsing ../input/gcamdata/xml/gas_trade.xml scenario component.
Parsing ../input/gcamdata/xml/prune_empty_ag.xml scenario component.
Parsing ../input/solution/cal_broyden_config.xml scenario component.
Parsing ../input/policy/ndc/buildings/zeb_target_constraint_EnhPol.xml scenario component.
Parsing ../input/policy/ndc/buildings/zeb_target_tech_EnhPol.xml scenario component.
XML parsing complete.
Starting new scenario: ZEB_EnhPol
Sat Jan 11 18:08:45 2025:WARNING:printLogHeader: hector version 3.2.0
Sat Jan 11 18:08:45 2025:WARNING:printLogHeader: hector version 3.2.0
Starting a model run. Running period 11
Model run beginning.
Period 0: 1975
Model solved with last period's prices.

Period 1: 1990
Model solved normally. Iterations period 1: 172. Total iterations: 173

Period 2: 2005
Model solved normally. Iterations period 2: 173. Total iterations: 346

Period 3: 2010
Model solved normally. Iterations period 3: 236. Total iterations: 581

Period 4: 2015
Model solved normally. Iterations period 4: 154. Total iterations: 735

Period 5: 2020
Model solved normally. Iterations period 5: 1725. Total iterations: 2460

Period 6: 2025
Model solved normally. Iterations period 6: 408. Total iterations: 2867

Period 7: 2030
Model solved normally. Iterations period 7: 251. Total iterations: 3118

Period 8: 2035
Model solved normally. Iterations period 8: 211. Total iterations: 3328

Period 9: 2040
Model solved normally. Iterations period 9: 743. Total iterations: 4070

Period 10: 2045
Input ZEB-Enhanced-Certification-Target does not have a matching input in the next period.
Model solved normally. Iterations period 10: 332. Total iterations: 4402

Period 11: 2050
Model solved normally. Iterations period 11: 418. Total iterations: 4819

All model periods solved correctly.
Sat Jan 11 18:13:42 2025:WARNING:printLogHeader: hector version 3.2.0
Model run completed.
Printing output
Starting output to XML Database.
Model run completed.
All model runs completed successfully.
Model exiting successfully.
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "WildcardExpandingClassLoader"). To use archived non-system classes, this property must be not be set

Command executed successfully!

In [165]:
os.chdir("../analyze/script-ndc/buildings")

# Model Result Validation

In [178]:
db_file = "database_basexdb_test"
db_path = proj_path / "output"
query_file = db_path / "queries" / "Main_queries.xml"
conn = gcamreader.LocalDBConn(db_path, db_file)
queries = gcamreader.parse_batch_query(query_file)

Database scenarios: ZEB_Reference, ZEB_CurPol, ZEB_EnhPol, ZEB_EnhPol

In [179]:
for i, q in enumerate(queries):
    print(i, q.title)

0 primary energy consumption by region (avg fossil efficiency)
1 primary energy consumption by region (direct equivalent)
2 primary energy consumption with CCS by region (direct equivalent)
3 resource production
4 resource production by tech and vintage
5 resource supply curves
6 regional primary energy prices
7 elec gen by region (incl CHP)
8 elec gen by subsector
9 elec gen by gen tech
10 elec gen by gen tech and cooling tech
11 elec gen by gen tech and cooling tech and vintage
12 elec gen by gen tech and cooling tech (new)
13 elec energy input by subsector
14 elec energy input by elec gen tech
15 elec energy input by elec gen tech and cooling tech
16 elec prices by sector
17 elec gen costs by subsector
18 elec gen costs by tech
19 elec gen costs by cooling tech
20 elec share-weights by subsector
21 elec share-weights by tech
22 elec share-weights by cooling tech
23 elec td inputs and outputs
24 cogeneration by region
25 elec consumption by demand sector
26 elec sector water withdrawals
27 elec sector water consumption
28 elec water withdrawals by gen tech
29 elec water consumption by gen tech
30 elec water withdrawals by gen tech and cooling tech
31 elec water consumption by gen tech and cooling tech
32 elec water withdrawals by gen tech and cooling tech (new)
33 elec water consumption by gen tech and cooling tech (new)
34 refined liquids production by region
35 refined liquids production by subsector
36 refined liquids production by tech
37 refined liquids production by tech and vintage
38 refined liquids production by tech (new)
39 refinery inputs by tech (energy and feedstocks)
40 refined liquids prices by sector
41 refined liquids costs by subsector
42 refined liquids costs by tech
43 refining and oil share-weights by subsector
44 refining share-weights by tech
45 hydrogen production by tech
46 hydrogen inputs by tech
47 hydrogen prices by sector
48 hydrogen costs by tech
49 hydrogen technology IO coefficients
50 hydrogen utilization by technology
51 hydrogen non-energy costs
52 hydrogen outputs by technology
53 hydrogen dispensing energy by primary fuel
54 gas production by tech
55 gas production share-weights by subsector
56 gas inputs by tech (energy and feedstocks)
57 gas pipeline inputs and outputs
58 gas prices by sector
59 gas costs by tech
60 gas consumption by sector
61 delivered gas energy by primary fuel
62 district heat production by subsector (fuel)
63 district heat energy inputs by subsector
64 total final energy by region
65 total final energy by aggregate sector
66 total final energy by sector
67 final energy consumption by fuel
68 final energy consumption by sector and fuel
69 final energy prices
70 building floorspace
71 building floorspace per capita
72 building commercial floorspace satiation impedance
73 building residential floorspace regional bias adder
74 building total final energy by region
75 building total final energy by service
76 building final energy by fuel
77 building final energy by service and fuel
78 building final energy by subsector
79 building final energy by tech
80 building final energy by tech and vintage
81 building final energy by tech (new)
82 building service output by service
83 building service output by subsector
84 building service output by tech
85 building service output by tech and vintage
86 building service output by tech (new)
87 building service density by energy service
88 building satiation impedance by energy service
89 building regional bias adder by energy service
90 building internal gain energy by service
91 total service cost per unit floorspace
92 building service costs
93 fuel prices to buildings
94 building share-weights by subsector
95 building share-weights by tech
96 industry total final energy by region
97 industry total final energy by service
98 industry final energy by fuel
99 industry final energy by service and fuel
100 industry final energy by tech and fuel
101 industry feedstocks by type
102 industry primary output by sector
103 industry cogeneration by fuel
104 fuel prices to industry
105 industry share-weights by subsector
106 industry water withdrawals and consumption
107 cement production by region
108 cement production by tech (conv and ccs)
109 cement production by tech and vintage
110 inputs to cement production
111 cement prices
112 ammonia production by region
113 ammonia production by tech
114 ammonia inputs by tech (energy and feedstocks)
115 ammonia and N fertilizer prices
116 ammonia domestic supply
117 ammonia exports (query USA region)
118 iron and steel production by region
119 iron and steel production by tech
120 iron and steel production by tech and vintage
121 iron and steel inputs by tech (energy and feedstocks)
122 iron and steel prices
123 traded iron and steel
124 regional iron and steel sources
125 chemical production by region
126 chemical inputs by tech (energy and feedstocks)
127 chemical prices
128 aluminum production by region
129 aluminum production by tech
130 aluminum production by tech and vintage
131 aluminum inputs by tech (energy and feedstocks)
132 aluminum prices
133 construction inputs (energy and feedstocks)
134 agricultural energy use
135 mining energy use
136 food processing production by region
137 food processing process heat production by tech
138 inputs to food processing
139 inputs to food processing (process heat separated)
140 food processing prices
141 paper production by region
142 inputs to paper production
143 paper prices
144 energy-for-water TFE
145 energy-for-water FE by fuel
146 energy-for-water FE by process and fuel
147 prices of energy-for-water processes
148 water flow volumes of EFW processes
149 nonrenewable groundwater pumping energy
150 transport total final energy by region
151 transport total final energy by service
152 transport final energy by fuel
153 transport final energy by mode and fuel
154 transport final energy by tech and fuel
155 transport final energy by tech and vintage
156 transport final energy by tech (new)
157 transport service output by service
158 transport service output by mode
159 transport service output by tech
160 transport service output by tech and vintage
161 transport service output by tech (new)
162 transport load factors
163 fuel prices to transport
164 costs of transport services
165 costs of transport modes
166 costs of transport techs
167 transport tech non-energy cost
168 LDV energy by primary fuel
169 transport subsector share-weights
170 transport tech share-weights
171 transport speeds
172 building final energy by tech
173 building service output by tech
174 building floorspace
175 industry final energy by service and fuel
176 transport final energy by tech and fuel
177 transport final energy by tech (new)
178 transport service output by tech
179 transport service output by tech (new)
180 detailed land allocation
181 detailed historical land allocation
182 land allocation by crop
183 aggregated land allocation
184 aggregated historical land allocation
185 land allocation in a specified land use region
186 land allocation by crop and water source
187 LUC emissions by region
188 LUC emissions by LUT
189 LUC emissions by LUT in a specified land use region
190 vegetative carbon stock by region
191 profit rate
192 profit rate in a specified land use region
193 land leaf shares
194 land leaf shares in a specified land use region
195 ag production by crop type
196 ag production by subsector (land use region)
197 ag production in a specified land use region
198 ag production by tech
199 ag tech variable cost
200 ag tech yield
201 ag tech yield in a specified land region
202 ag commodity prices
203 ag tech implied subsidy
204 irrigation water withdrawals by region
205 irrigation water withdrawals by crop type
206 irrigation water withdrawals by crop type and land region
207 irrigation water withdrawals by ag tech
208 irrigation water consumption by region
209 irrigation water consumption by crop type
210 irrigation water consumption by crop type and land region
211 irrigation water consumption by ag tech
212 biophysical water demand by region
213 biophysical water demand by crop type
214 biophysical water demand by crop type and land region
215 biophysical water demand by ag tech
216 fertilizer consumption by region
217 fertilizer consumption by crop type
218 fertilizer consumption by ag tech
219 fertilizer-crop input-output coefficients
220 purpose-grown biomass production
221 residue biomass production
222 MSW production
223 regional biomass consumption
224 meat and dairy production by type
225 meat and dairy production by tech
226 meat and dairy prices
227 meat and dairy subsector share-weights
228 meat and dairy tech share-weights
229 meat and dairy subsector costs
230 meat and dairy tech costs
231 water consumption by meat and dairy production
232 feed consumption by region
233 feed consumption by meat and dairy tech
234 feed sources
235 feed prices
236 feed subsector share-weights
237 food consumption by type (general)
238 food consumption by type (specific)
239 demand balances by crop commodity
240 demand balances by meat and dairy commodity
241 food demand prices
242 food demand
243 food demand per capita
244 food demand regional bias
245 ag import vs. domestic supply (Regional Armington competition)
246 ag export to the world center (USA) (Intl. Armington competition)
247 ag import vs. domestic prices
248 ag export prices (at world center USA)
249 import vs. domestic share-weights (Armington regional taste)
250 international competition share-weights (Armington intl. taste)
251 ag total prices (weighted average b/t domestic and imported prices)
252 opening stocks (supply from carryover)
253 closing stocks (before loss/adjustments)
254 closing stocks (after loss/adjustments; carried over)
255 current supply (current or regional consumption)
256 ag regional prices (current consumer prices)
257 agricultural storage share-weights
258 storage cost
259 expected price
260 CO2 emissions by region
261 CO2 emissions by sector (excluding resource production)
262 CO2 emissions by sector (no bio) (excluding resource production)
263 CO2 emissions by assigned sector (no bio) (excluding resource production)
264 CO2 emissions by subsector (excluding resource production)
265 CO2 emissions by tech (excluding resource production)
266 CO2 emissions by resource production
267 CO2 sequestration by sector
268 CO2 sequestration by tech
269 nonCO2 emissions by region
270 nonCO2 emissions by sector (excluding resource production)
271 nonCO2 emissions by resource production
272 nonCO2 emissions by subsector (excluding resource production)
273 nonCO2 emissions by tech (excluding resource production)
274 specific nonCO2 emissions by region
275 specific nonCO2 emissions by sector (excluding resource production)
276 specific nonCO2 emissions by resource production
277 specific nonCO2 emissions by subsector (excluding resource production)
278 specific nonCO2 emissions by tech (excluding resource production)
279 CO2 concentrations
280 total climate forcing
281 global mean temperature
282 net terrestrial C uptake
283 population by region
284 GDP MER by region
285 GDP per capita MER by region
286 GDP per capita PPP by region
287 subregional population
288 subregional income
289 National Account
290 Social Accounting Matrix
291 Tracking accounts by tech
292 Capital investment demands by tech
293 Capital investment demands by resource
294 CO2 prices
295 policy cost by period
296 undiscounted policy cost
297 discounted policy cost
298 regional CO2 MAC curves by period
299 water withdrawals by region
300 water withdrawals by water mapping source
301 water withdrawals by sector
302 water withdrawals by subsector
303 water withdrawals by tech
304 water consumption by region
305 water consumption by water mapping source
306 water consumption by sector
307 water consumption by subsector
308 water consumption by tech
309 Basin level available runoff
310 Water withdrawals by water source (runoff vs. groundwater)
311 Water Withdrawals by Basin (Runoff)
312 Water Withdrawals by Basin (Groundwater)
313 Cumulative groundwater extraction
314 prices of all markets
315 supply of all markets
316 demand of all markets
317 price of a specific market
318 supply of a specific market
319 prices by sector
320 costs by subsector
321 costs by tech
322 costs by tech and input
323 inputs by sector
324 inputs by subsector
325 inputs by tech
326 outputs by sector
327 outputs by subsector
328 outputs by tech
329 input-output coefficients by tech
330 primary energy consumption by region (direct equivalent)
331 industry water withdrawals and consumption
332 elec gen by region (no CHP)
333 elec gen by subsector
334 elec gen by gen tech (cogen only)
335 elec gen by gen tech and cooling tech (incl cogen)
336 elec energy input by subsector
337 elec energy input by elec gen tech
338 elec prices by sector
339 elec gen costs by subsector
340 elec gen costs by tech
341 elec share-weights by subsector
342 elec share-weights by gen tech
343 elec share-weights by cooling tech
344 elec water withdrawals by gen tech and cooling tech
345 elec water consumption by gen tech and cooling tech
346 refined liquids production by region
347 refined liquids production by subsector
348 refined liquids production by tech
349 refined liquids production by tech and vintage
350 refined liquids production by tech (new)
351 refinery inputs by tech (energy and feedstocks)
352 refined liquids prices by sector
353 refined liquids costs by subsector
354 refined liquids costs by tech
355 refining and oil share-weights by subsector
356 refining share-weights by tech
357 total final energy by aggregate sector
358 water withdrawals by state, sector, basin
359 water withdrawals by state, sector, basin (includes desal)
360 water consumption by state, sector, basin
361 water consumption by state, sector, basin (includes desal)
362 CO2 emissions by tech (nested subsector) (excluding resource production)
363 CO2 sequestration by tech (nested subsector)

In [180]:
q = queries[9]
print(q.title)
dfGen = conn.runQuery(query=q, scenarios=['ZEB_Reference', 'ZEB_CurPol', 'ZEB_EnhPol'], regions=['South Korea'])
dfGen['scenario'] = dfGen['scenario'].str.split(',').str[0]
dfGen.head()

elec gen by gen tech

,Units,scenario,region,subsector,technology,output,Year,value
0,EJ,ZEB_CurPol,South Korea,biomass,biomass (IGCC),electricity,2025,0.000413
1,EJ,ZEB_CurPol,South Korea,biomass,biomass (IGCC),electricity,2030,0.001068
2,EJ,ZEB_CurPol,South Korea,biomass,biomass (IGCC),electricity,2035,0.001997
3,EJ,ZEB_CurPol,South Korea,biomass,biomass (IGCC),electricity,2040,0.003188
4,EJ,ZEB_CurPol,South Korea,biomass,biomass (IGCC),electricity,2045,0.004496

In [181]:
dfGen['technology'].unique()

array(['biomass (IGCC)', 'biomass (conv)', 'coal (IGCC)',
       'coal (conv pul)', 'gas (CC)', 'gas (steam/CT)', 'hydro',
       'Gen_III', 'Gen_II_LWR', 'refined liquids (CC)',
       'refined liquids (steam/CT)', 'rooftop_pv', 'CSP_storage', 'PV',
       'PV_storage', 'wind', 'wind_offshore', 'wind_storage'],
      dtype=object)

In [182]:
dfGen[(dfGen['Year'] >= 2020) & (dfGen['technology'] == 'rooftop_pv')].groupby(['Year', 'scenario'])['value'].sum()

Year  scenario
2020  ZEB_CurPol       0.002308
      ZEB_EnhPol       0.002308
      ZEB_Reference    0.002308
2025  ZEB_CurPol       0.019953
      ZEB_EnhPol       0.019953
      ZEB_Reference    0.017475
2030  ZEB_CurPol       0.057694
      ZEB_EnhPol       0.093517
      ZEB_Reference    0.050636
2035  ZEB_CurPol       0.097082
      ZEB_EnhPol       0.170335
      ZEB_Reference    0.085309
2040  ZEB_CurPol       0.119796
      ZEB_EnhPol       0.229806
      ZEB_Reference    0.103447
2045  ZEB_CurPol       0.116365
      ZEB_EnhPol       0.124262
      ZEB_Reference    0.115052
2050  ZEB_CurPol       0.120736
      ZEB_EnhPol       0.128216
      ZEB_Reference    0.119492
Name: value, dtype: float64